/**
 ** This file was automatically generated by the Cyclone scheme compiler
 ** http://justinethier.github.io/cyclone/
 **
 ** (c) 2014-2021 Justin Ethier
 ** Version 0.28.0 
 **
 **/

#define closcall1(td, clo, buf) \
if (obj_is_not_closure(clo)) { \
   Cyc_apply(td, clo, 1, buf ); \
} else { \
   ((clo)->fn)(td, clo, 1, buf); \
;\
}
#define return_closcall1(td, clo,a1) { \
 char top; \
 object buf[1]; buf[0] = a1;\
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     GC(td, clo, buf, 1); \
     return; \
 } else {\
     closcall1(td, (closure) (clo), buf); \
     return;\
 } \
}

#define continue_or_gc1(td, clo,a1) { \
 char *top = alloca(sizeof(char)); \
 if (stack_overflow(top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[1]; buf[0] = a1;\
     GC(td, clo, buf, 1); \
     return; \
 } else {\
     continue;\
 } \
}

#define return_direct1(td, _fn,a1) { \
 char top; \
 object buf[1]; buf[0] = a1; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     mclosure0(c1, (function_type) _fn); \
     GC(td, &c1, buf, 1); \
     return; \
 } else { \
     (_fn)(td, (closure)_fn, 1, buf); \
 }}

#define return_direct_with_clo1(td, clo, _fn,a1) { \
 char top; \
 object buf[1]; buf[0] = a1;\
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     GC(td, clo, buf, 1); \
     return; \
 } else { \
     (_fn)(td, (closure)(clo), 1, buf); \
 }}

#define closcall2(td, clo, buf) \
if (obj_is_not_closure(clo)) { \
   Cyc_apply(td, clo, 2, buf ); \
} else { \
   ((clo)->fn)(td, clo, 2, buf); \
;\
}
#define return_closcall2(td, clo,a1,a2) { \
 char top; \
 object buf[2]; buf[0] = a1;buf[1] = a2;\
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     GC(td, clo, buf, 2); \
     return; \
 } else {\
     closcall2(td, (closure) (clo), buf); \
     return;\
 } \
}

#define continue_or_gc2(td, clo,a1,a2) { \
 char *top = alloca(sizeof(char)); \
 if (stack_overflow(top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[2]; buf[0] = a1;buf[1] = a2;\
     GC(td, clo, buf, 2); \
     return; \
 } else {\
     continue;\
 } \
}

#define return_direct2(td, _fn,a1,a2) { \
 char top; \
 object buf[2]; buf[0] = a1;buf[1] = a2; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     mclosure0(c1, (function_type) _fn); \
     GC(td, &c1, buf, 2); \
     return; \
 } else { \
     (_fn)(td, (closure)_fn, 2, buf); \
 }}

#define return_direct_with_clo2(td, clo, _fn,a1,a2) { \
 char top; \
 object buf[2]; buf[0] = a1;buf[1] = a2;\
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     GC(td, clo, buf, 2); \
     return; \
 } else { \
     (_fn)(td, (closure)(clo), 2, buf); \
 }}

#define closcall3(td, clo, buf) \
if (obj_is_not_closure(clo)) { \
   Cyc_apply(td, clo, 3, buf ); \
} else { \
   ((clo)->fn)(td, clo, 3, buf); \
;\
}
#define return_closcall3(td, clo,a1,a2,a3) { \
 char top; \
 object buf[3]; buf[0] = a1;buf[1] = a2;buf[2] = a3;\
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     GC(td, clo, buf, 3); \
     return; \
 } else {\
     closcall3(td, (closure) (clo), buf); \
     return;\
 } \
}

#define continue_or_gc3(td, clo,a1,a2,a3) { \
 char *top = alloca(sizeof(char)); \
 if (stack_overflow(top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[3]; buf[0] = a1;buf[1] = a2;buf[2] = a3;\
     GC(td, clo, buf, 3); \
     return; \
 } else {\
     continue;\
 } \
}

#define return_direct3(td, _fn,a1,a2,a3) { \
 char top; \
 object buf[3]; buf[0] = a1;buf[1] = a2;buf[2] = a3; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     mclosure0(c1, (function_type) _fn); \
     GC(td, &c1, buf, 3); \
     return; \
 } else { \
     (_fn)(td, (closure)_fn, 3, buf); \
 }}

#define return_direct_with_clo3(td, clo, _fn,a1,a2,a3) { \
 char top; \
 object buf[3]; buf[0] = a1;buf[1] = a2;buf[2] = a3;\
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     GC(td, clo, buf, 3); \
     return; \
 } else { \
     (_fn)(td, (closure)(clo), 3, buf); \
 }}

#include <emscripten.h>
#include "ck-polyfill.h"
#include "terminal.h"
#include "cyclone/types.h"
object __glo_loop = NULL;
object __glo_display_91help_91for_91cmd = NULL;
object __glo_ready_91for_91more_91input = NULL;
object __glo_get_91input = NULL;
object __glo__75help = NULL;
object __glo_help = NULL;
object __glo__85site_91url_85 = NULL;
extern object __glo_member_scheme_base;
extern object __glo_assoc_scheme_base;
extern object __glo_cons_91source_scheme_base;
extern object __glo_syntax_91rules_scheme_base;
extern object __glo_letrec_85_scheme_base;
extern object __glo_guard_scheme_base;
extern object __glo_guard_91aux_scheme_base;
extern object __glo_define_91record_91type_scheme_base;
extern object __glo_record_127_scheme_base;
extern object __glo_is_91a_127_scheme_base;
extern object __glo_register_91simple_91type_scheme_base;
extern object __glo_make_91type_91predicate_scheme_base;
extern object __glo_make_91constructor_scheme_base;
extern object __glo_make_91constructor_95args_scheme_base;
extern object __glo_make_91getter_scheme_base;
extern object __glo_make_91setter_scheme_base;
extern object __glo_slot_91ref_scheme_base;
extern object __glo_slot_91set_67_scheme_base;
extern object __glo_type_91slot_91offset_scheme_base;
extern object __glo_make_91record_91marker_scheme_base;
extern object __glo_receive_scheme_base;
extern object __glo_abs_scheme_base;
extern object __glo_max_scheme_base;
extern object __glo_min_scheme_base;
extern object __glo_modulo_scheme_base;
extern object __glo_floor_91remainder_scheme_base;
extern object __glo_even_127_scheme_base;
extern object __glo_exact_91integer_127_scheme_base;
extern object __glo_exact_91integer_91sqrt_scheme_base;
extern object __glo_exact_127_scheme_base;
extern object __glo_inexact_127_scheme_base;
extern object __glo_odd_127_scheme_base;
extern object __glo_complex_127_scheme_base;
extern object __glo_rational_127_scheme_base;
extern object __glo_bignum_127_scheme_base;
extern object __glo_gcd_scheme_base;
extern object __glo_lcm_scheme_base;
extern object __glo_quotient_scheme_base;
extern object __glo_remainder_scheme_base;
extern object __glo_truncate_91quotient_scheme_base;
extern object __glo_truncate_91remainder_scheme_base;
extern object __glo_truncate_95_scheme_base;
extern object __glo_floor_91quotient_scheme_base;
extern object __glo_floor_91remainder_scheme_base;
extern object __glo_floor_95_scheme_base;
extern object __glo_square_scheme_base;
extern object __glo_expt_scheme_base;
extern object __glo_call_91with_91current_91continuation_scheme_base;
extern object __glo_call_95cc_scheme_base;
extern object __glo_call_91with_91values_scheme_base;
extern object __glo_dynamic_91wind_scheme_base;
extern object __glo_values_scheme_base;
extern object __glo_char_123_127_scheme_base;
extern object __glo_char_121_127_scheme_base;
extern object __glo_char_125_127_scheme_base;
extern object __glo_char_121_123_127_scheme_base;
extern object __glo_char_125_123_127_scheme_base;
extern object __glo_string_123_127_scheme_base;
extern object __glo_string_121_127_scheme_base;
extern object __glo_string_121_123_127_scheme_base;
extern object __glo_string_125_127_scheme_base;
extern object __glo_string_125_123_127_scheme_base;
extern object __glo_fast_91string_123_127_scheme_base;
extern object __glo_fast_91string_121_127_scheme_base;
extern object __glo_fast_91string_121_123_127_scheme_base;
extern object __glo_fast_91string_125_127_scheme_base;
extern object __glo_fast_91string_125_123_127_scheme_base;
extern object __glo_foldl_scheme_base;
extern object __glo_foldr_scheme_base;
extern object __glo_not_scheme_base;
extern object __glo_list_127_scheme_base;
extern object __glo_zero_127_scheme_base;
extern object __glo_positive_127_scheme_base;
extern object __glo_negative_127_scheme_base;
extern object __glo_append_scheme_base;
extern object __glo__list_scheme_base;
extern object __glo_make_91list_scheme_base;
extern object __glo_list_91copy_scheme_base;
extern object __glo_map_scheme_base;
extern object __glo_Cyc_91map_91loop_911_scheme_base;
extern object __glo_Cyc_91map_91loop_912_scheme_base;
extern object __glo_Cyc_91for_91each_91loop_911_scheme_base;
extern object __glo_Cyc_91for_91each_91loop_912_scheme_base;
extern object __glo_for_91each_scheme_base;
extern object __glo_list_91tail_scheme_base;
extern object __glo_list_91ref_scheme_base;
extern object __glo_list_91set_67_scheme_base;
extern object __glo_reverse_scheme_base;
extern object __glo_boolean_123_127_scheme_base;
extern object __glo_symbol_123_127_scheme_base;
extern object __glo_Cyc_91obj_123_127_scheme_base;
extern object __glo_vector_scheme_base;
extern object __glo_vector_91append_scheme_base;
extern object __glo_vector_91copy_scheme_base;
extern object __glo_vector_91copy_67_scheme_base;
extern object __glo_vector_91fill_67_scheme_base;
extern object __glo_vector_91_125list_scheme_base;
extern object __glo_vector_91_125string_scheme_base;
extern object __glo_vector_91map_scheme_base;
extern object __glo_vector_91for_91each_scheme_base;
extern object __glo_make_91string_scheme_base;
extern object __glo_string_scheme_base;
extern object __glo_string_91copy_scheme_base;
extern object __glo_string_91copy_67_scheme_base;
extern object __glo_string_91fill_67_scheme_base;
extern object __glo_string_91_125list_scheme_base;
extern object __glo_string_91_125vector_scheme_base;
extern object __glo_string_91map_scheme_base;
extern object __glo_string_91for_91each_scheme_base;
extern object __glo_make_91parameter_scheme_base;
extern object __glo_current_91output_91port_scheme_base;
extern object __glo_current_91input_91port_scheme_base;
extern object __glo_current_91error_91port_scheme_base;
extern object __glo_call_91with_91port_scheme_base;
extern object __glo_error_91object_127_scheme_base;
extern object __glo_error_91object_91message_scheme_base;
extern object __glo_error_91object_91irritants_scheme_base;
extern object __glo_error_95loc_scheme_base;
extern object __glo_error_scheme_base;
extern object __glo_raise_scheme_base;
extern object __glo_raise_91continuable_scheme_base;
extern object __glo_with_91handler_scheme_base;
extern object __glo_with_91exception_91handler_scheme_base;
extern object __glo_Cyc_91add_91exception_91handler_scheme_base;
extern object __glo_Cyc_91remove_91exception_91handler_scheme_base;
extern object __glo_newline_scheme_base;
extern object __glo_write_91char_scheme_base;
extern object __glo_write_91string_scheme_base;
extern object __glo_write_91string_911_scheme_base;
extern object __glo_write_91string_912_scheme_base;
extern object __glo_flush_91output_91port_scheme_base;
extern object __glo_peek_91char_scheme_base;
extern object __glo_read_91char_scheme_base;
extern object __glo_read_91line_scheme_base;
extern object __glo_read_91string_scheme_base;
extern object __glo_input_91port_127_scheme_base;
extern object __glo_output_91port_127_scheme_base;
extern object __glo_input_91port_91open_127_scheme_base;
extern object __glo_output_91port_91open_127_scheme_base;
extern object __glo_get_91output_91string_scheme_base;
extern object __glo_open_91output_91string_scheme_base;
extern object __glo_open_91input_91string_scheme_base;
extern object __glo_get_91output_91bytevector_scheme_base;
extern object __glo_open_91input_91bytevector_scheme_base;
extern object __glo_open_91output_91bytevector_scheme_base;
extern object __glo_features_scheme_base;
extern object __glo_Cyc_91add_91feature_67_scheme_base;
extern object __glo_Cyc_91version_scheme_base;
extern object __glo_any_scheme_base;
extern object __glo_every_scheme_base;
extern object __glo_and_scheme_base;
extern object __glo_or_scheme_base;
extern object __glo_let_scheme_base;
extern object __glo_let_85_scheme_base;
extern object __glo_letrec_scheme_base;
extern object __glo_let_85_91values_scheme_base;
extern object __glo_let_91values_scheme_base;
extern object __glo_define_91values_scheme_base;
extern object __glo_begin_scheme_base;
extern object __glo__case_scheme_base;
extern object __glo_cond_scheme_base;
extern object __glo_cond_91expand_scheme_base;
extern object __glo__do_scheme_base;
extern object __glo_when_scheme_base;
extern object __glo_unless_scheme_base;
extern object __glo_quasiquote_scheme_base;
extern object __glo_floor_scheme_base;
extern object __glo_ceiling_scheme_base;
extern object __glo_truncate_scheme_base;
extern object __glo_round_scheme_base;
extern object __glo_exact_scheme_base;
extern object __glo_inexact_scheme_base;
extern object __glo_eof_91object_scheme_base;
extern object __glo__void_scheme_base;
extern object __glo_syntax_91error_scheme_base;
extern object __glo_bytevector_91copy_scheme_base;
extern object __glo_bytevector_91copy_67_scheme_base;
extern object __glo_utf8_91_125string_scheme_base;
extern object __glo_string_91_125utf8_scheme_base;
extern object __glo_denominator_scheme_base;
extern object __glo_numerator_scheme_base;
extern object __glo_parameterize_scheme_base;
extern object __glo_read_91bytevector_scheme_base;
extern object __glo_read_91bytevector_67_scheme_base;
extern object __glo_write_91bytevector_scheme_base;
extern object __glo_peek_91u8_scheme_base;
extern object __glo_read_91u8_scheme_base;
extern object __glo_write_91u8_scheme_base;
extern object __glo_binary_91port_127_scheme_base;
extern object __glo_textual_91port_127_scheme_base;
extern object __glo_read_scheme_read;
extern object __glo_read_91all_scheme_read;
extern object __glo_read_91all_95source_scheme_read;
extern object __glo_include_scheme_read;
extern object __glo_include_91ci_scheme_read;
extern object __glo_display_scheme_write;
extern object __glo_write_scheme_write;
extern object __glo_write_91shared_scheme_write;
extern object __glo_write_91simple_scheme_write;
extern object __glo_eval_scheme_eval;
extern object __glo_eval_91from_91c_scheme_eval;
extern object __glo_create_91environment_scheme_eval;
extern object __glo_setup_91environment_scheme_eval;
extern object __glo__75import_scheme_eval;
extern object __glo_imported_127_scheme_eval;
extern object __glo__75set_91import_91dirs_67_scheme_eval;
extern object __glo_import_91shared_91object_scheme_eval;
extern object __glo__85defined_91macros_85_scheme_eval;
extern object __glo_get_91macros_scheme_eval;
extern object __glo_macro_117macro_127_scheme_eval;
extern object __glo_macro_117expand_scheme_eval;
extern object __glo_macro_117add_67_scheme_eval;
extern object __glo_macro_117cleanup_scheme_eval;
extern object __glo_macro_117load_91env_67_scheme_eval;
extern object __glo_macro_117get_91env_scheme_eval;
extern object __glo_macro_117get_91defined_91macros_scheme_eval;
extern object __glo_expand_scheme_eval;
extern object __glo_expand_91lambda_91body_scheme_eval;
extern object __glo_thread_127_srfi_18;
extern object __glo_make_91thread_srfi_18;
extern object __glo_thread_91name_srfi_18;
extern object __glo_thread_91specific_srfi_18;
extern object __glo_thread_91specific_91set_67_srfi_18;
extern object __glo_thread_91start_67_srfi_18;
extern object __glo_thread_91sleep_67_srfi_18;
extern object __glo_thread_91yield_67_srfi_18;
extern object __glo_thread_91terminate_67_srfi_18;
extern object __glo_current_91thread_srfi_18;
extern object __glo_current_91thread_91data_srfi_18;
extern object __glo_thread_91join_67_srfi_18;
extern object __glo_mutex_127_srfi_18;
extern object __glo_make_91mutex_srfi_18;
extern object __glo_mutex_91lock_67_srfi_18;
extern object __glo_mutex_91unlock_67_srfi_18;
extern object __glo_condition_91variable_127_srfi_18;
extern object __glo_make_91condition_91variable_srfi_18;
extern object __glo_condition_91variable_91wait_67_srfi_18;
extern object __glo_condition_91variable_91signal_67_srfi_18;
extern object __glo_condition_91variable_91broadcast_67_srfi_18;
extern object __glo__91_125heap_srfi_18;
extern object __glo_Cyc_91minor_91gc_srfi_18;
extern object __glo_fast_91string_123_127_191_191inline_191_191_scheme_base;
extern object __glo_fast_91string_121_127_191_191inline_191_191_scheme_base;
extern object __glo_fast_91string_121_123_127_191_191inline_191_191_scheme_base;
extern object __glo_fast_91string_125_127_191_191inline_191_191_scheme_base;
extern object __glo_fast_91string_125_123_127_191_191inline_191_191_scheme_base;
extern object __glo__75write_91bytevector_191_191inline_191_191_scheme_base;
extern object __glo_not_191_191inline_191_191_scheme_base;
extern object __glo_list_127_191_191inline_191_191_scheme_base;
extern object __glo_zero_127_191_191inline_191_191_scheme_base;
extern object __glo_positive_127_191_191inline_191_191_scheme_base;
extern object __glo_negative_127_191_191inline_191_191_scheme_base;
extern object __glo_floor_191_191inline_191_191_scheme_base;
extern object __glo_ceiling_191_191inline_191_191_scheme_base;
extern object __glo_truncate_191_191inline_191_191_scheme_base;
extern object __glo_round_191_191inline_191_191_scheme_base;
extern object __glo_inexact_191_191inline_191_191_scheme_base;
extern object __glo_sqrt_191_191inline_191_191_scheme_base;
extern object __glo_exact_91integer_127_191_191inline_191_191_scheme_base;
extern object __glo_exact_127_191_191inline_191_191_scheme_base;
extern object __glo_complex_127_191_191inline_191_191_scheme_base;
extern object __glo_denominator_191_191inline_191_191_scheme_base;
extern object __glo_numerator_191_191inline_191_191_scheme_base;
extern object __glo_quotient_191_191inline_191_191_scheme_base;
extern object __glo_square_191_191inline_191_191_scheme_base;
extern object __glo_eof_91object_191_191inline_191_191_scheme_base;
extern object __glo_void_191_191inline_191_191_scheme_base;
extern object __glo_make_91record_91marker_191_191inline_191_191_scheme_base;
extern object __glo_Cyc_91opaque_91eq_127_191_191inline_191_191_scheme_read;
extern object __glo_Cyc_91opaque_91unsafe_91eq_127_191_191inline_191_191_scheme_read;
extern object __glo_Cyc_91opaque_91unsafe_91string_127_191_191inline_191_191_scheme_read;
extern object __glo_variable_127_191_191inline_191_191_scheme_eval;
extern object __glo_assignment_91variable_191_191inline_191_191_scheme_eval;
extern object __glo_assignment_91value_191_191inline_191_191_scheme_eval;
extern object __glo_definition_91variable_191_191inline_191_191_scheme_eval;
extern object __glo_lambda_91parameters_191_191inline_191_191_scheme_eval;
extern object __glo_lambda_91body_191_191inline_191_191_scheme_eval;
extern object __glo_if_91predicate_191_191inline_191_191_scheme_eval;
extern object __glo_if_91consequent_191_191inline_191_191_scheme_eval;
extern object __glo_if_91alternative_191_191inline_191_191_scheme_eval;
extern object __glo_application_127_191_191inline_191_191_scheme_eval;
extern object __glo_operator_191_191inline_191_191_scheme_eval;
extern object __glo_operands_191_191inline_191_191_scheme_eval;
extern object __glo_procedure_91parameters_191_191inline_191_191_scheme_eval;
extern object __glo_procedure_91body_191_191inline_191_191_scheme_eval;
extern object __glo_procedure_91environment_191_191inline_191_191_scheme_eval;
extern object __glo_primitive_91implementation_191_191inline_191_191_scheme_eval;
extern object __glo_macro_117macro_127_191_191inline_191_191_scheme_eval;
#include "cyclone/runtime.h"
#include "cyclone/runtime-main.h"
defsymbol(quote);
defsymbol(_75help);
static void __lambda_52(void *data, object clo, int argc, object *args) ;/*object self_73197, object r_73145*/
static void __lambda_53(void *data, object clo, int argc, object *args) ;/*object self_73198, object r_73146*/
static void __lambda_54(void *data, object clo, int argc, object *args) ;/*object self_73199, object r_73147*/
static void __lambda_5(void *data, object clo, int argc, object *args) ;/*closure _,object k_7393*/
static void __lambda_7(void *data, object clo, int argc, object *args) ;/*object self_73150, object k_7395, object k_7317_7354*/
static void __lambda_22(void *data, object clo, int argc, object *args) ;/*object self_73151, object k_73111, object obj_7318_7355*/
static void __lambda_23(void *data, object clo, int argc, object *args) ;/*object self_73152, object obj_7319_7356*/
static void __lambda_55(void *data, object clo, int argc, object *args) ;/*object self_73153, object obj_7319_7356*/
static void __lambda_24(void *data, object clo, int argc, object *args) ;/*object self_73154, object r_73113*/
static void __lambda_48(void *data, object clo, int argc, object *args) ;/*object self_73155, object r_73114*/
static void __lambda_49(void *data, object clo, int argc, object *args) ;/*object self_73156, object r_73115*/
static void __lambda_50(void *data, object clo, int argc, object *args) ;/*object self_73157, object r_73116*/
static void __lambda_51(void *data, object clo, int argc, object *args) ;/*object self_73158, object r_73112*/
static void __lambda_25(void *data, object clo, int argc, object *args) ;/*object self_73159, object k_73117*/
static void __lambda_26(void *data, object clo, int argc, object *args) ;/*object self_73160, object r_73118*/
static void __lambda_36(void *data, object clo, int argc, object *args) ;/*object self_73170, object r_73129*/
static void __lambda_44(void *data, object clo, int argc, object *args) ;/*object self_73171, object r_73130*/
static void __lambda_46(void *data, object clo, int argc, object *args) ;/*object self_73172, object k_73132, object o_7327_7358*/
static void __lambda_47(void *data, object clo, int argc, object *args) ;/*object self_73173, object r_73133*/
static void __lambda_45(void *data, object clo, int argc, object *args) ;/*object self_73174, object r_73131*/
static void __lambda_37(void *data, object clo, int argc, object *args) ;/*object self_73175, object k_73134*/
static void __lambda_38(void *data, object clo, int argc, object *args) ;/*object self_73176, object r_73143*/
static void __lambda_39(void *data, object clo, int argc, object *args) ;/*object self_73177, object r_73142*/
static void __lambda_40(void *data, object clo, int argc, object *args) ;/*object self_73178, object r_73136*/
static void __lambda_42(void *data, object clo, int argc, object *args) ;/*object self_73179, object r_73137*/
static void __lambda_43(void *data, object clo, int argc, object *args) ;/*object self_73180, object r_73138*/
static void __lambda_41(void *data, object clo, int argc, object *args) ;/*object self_73181, object k_73139*/
static void __lambda_27(void *data, object clo, int argc, object *args) ;/*object self_73161, object r_73128*/
static void __lambda_28(void *data, object clo, int argc, object *args) ;/*object self_73162, object r_73119*/
static void __lambda_31(void *data, object clo, int argc, object *args) ;/*object self_73163, object r_73120*/
static void __lambda_34(void *data, object clo, int argc, object *args) ;/*object self_73164, object k_73123, object o_7323_7357*/
static void __lambda_35(void *data, object clo, int argc, object *args) ;/*object self_73165, object r_73124*/
static void __lambda_32(void *data, object clo, int argc, object *args) ;/*object self_73166, object r_73121*/
static void __lambda_33(void *data, object clo, int argc, object *args) ;/*object self_73167, object r_73122*/
static void __lambda_29(void *data, object clo, int argc, object *args) ;/*object self_73168, object k_73125*/
static void __lambda_30(void *data, object clo, int argc, object *args) ;/*object self_73169, object r_73127*/
static void __lambda_8(void *data, object clo, int argc, object *args) ;/*object self_73182, object r_7396*/
static void __lambda_10(void *data, object clo, int argc, object *args) ;/*object self_73183, object k_7398*/
static void __lambda_11(void *data, object clo, int argc, object *args) ;/*object self_73184, object str_7329_7359*/
static void __lambda_20(void *data, object clo, int argc, object *args) ;/*object self_73185, object r_7399*/
static void __lambda_21(void *data, object clo, int argc, object *args) ;/*object self_73186, object r_73100*/
static void __lambda_12(void *data, object clo, int argc, object *args) ;/*object self_73187, object k_73102*/
static void __lambda_13(void *data, object clo, int argc, object *args) ;/*object self_73188, object fp_7332_7360*/
static void __lambda_14(void *data, object clo, int argc, object *args) ;/*object self_73189, object sexp_91lis_7335_7361*/
static void __lambda_17(void *data, object clo, int argc, object *args) ;/*object self_73190, object k_73108, object sexp_7337_7362*/
static void __lambda_18(void *data, object clo, int argc, object *args) ;/*object self_73191, object obj_7338_7363*/
static void __lambda_19(void *data, object clo, int argc, object *args) ;/*object self_73192, object r_73110*/
static void __lambda_15(void *data, object clo, int argc, object *args) ;/*object self_73193, object r_73107*/
static void __lambda_16(void *data, object clo, int argc, object *args) ;/*object self_73194, object r_73106*/
static void __lambda_9(void *data, object clo, int argc, object *args) ;/*object self_73195, object r_7397*/
static void __lambda_6(void *data, object clo, int argc, object *args) ;/*object self_73196, object r_7394*/
static void __lambda_58(void *data, object clo, int argc, object *args) ;/*(void *data, object _, int argc, object *args)*/
static void __lambda_57(void *data, object clo, int argc, object *args) ;/*(void *data, object _, int argc, object *args)*/
static void __lambda_56(void *data, object clo, int argc, object *args) ;/*(void *data, object _, int argc, object *args)*/
static void __lambda_2(void *data, object clo, int argc, object *args) ;/*closure _,object k_7383, object opts_7311_7353_raw, ...*/
static void __lambda_4(void *data, object clo, int argc, object *args) ;/*object self_73149, object r_7387*/
static void __lambda_3(void *data, object clo, int argc, object *args) ;/*object self_73148, object r_7385*/
static void __lambda_1(void *data, object clo, int argc, object *args) ;/*closure _,object k_7368, object expr_731_7349, object rename_732_7350, object compare_733_7351*/

static void __lambda_52(void *data, object self_73197, int argc, object *args) /* object self_73197, object r_73145 */
 {

  
mclosure0(c_73493, (function_type)__lambda_53);c_73493.num_args = 1;
return_closcall1(data,  __glo_ready_91for_91more_91input,  &c_73493);; 
}

static void __lambda_53(void *data, object self_73198, int argc, object *args) /* object self_73198, object r_73146 */
 {

  
mclosure0(c_73495, (function_type)__lambda_54);c_73495.num_args = 1;
return_closcall1(data,  __glo_loop,  &c_73495);; 
}

static void __lambda_54(void *data, object self_73199, int argc, object *args) /* object self_73199, object r_73147 */
 {

  
  
  __halt(__halt(obj_int2obj(0)));; 
}

static void __lambda_5(void *data, object _, int argc, object *args) /* closure _,object k_7393 */
 {
object k_7393 = args[0];
  Cyc_st_add(data, "src/terminal.scm:loop");

closureN_type c_73262;
object e_73265 [1];
c_73262.hdr.mark = gc_color_red;
 c_73262.hdr.grayed = 0;
c_73262.tag = closureN_tag;
 c_73262.fn = (function_type)__lambda_6;
c_73262.num_args = 1;
c_73262.num_elements = 1;
c_73262.elements = (object *)e_73265;
c_73262.elements[0] = k_7393;


mclosure0(c_73266, (function_type)__lambda_7);c_73266.num_args = 1;
return_direct_with_clo1(data,(closure)&c_73262,__lambda_6,  &c_73266);; 
}

static void __lambda_7(void *data, object self_73150, int argc, object *args) /* object self_73150, object k_7395, object k_7317_7354 */
 {
 object k_7395 = args[0]; object k_7317_7354 = args[1];
  
closureN_type c_73268;
object e_73321 [1];
c_73268.hdr.mark = gc_color_red;
 c_73268.hdr.grayed = 0;
c_73268.tag = closureN_tag;
 c_73268.fn = (function_type)__lambda_8;
c_73268.num_args = 1;
c_73268.num_elements = 1;
c_73268.elements = (object *)e_73321;
c_73268.elements[0] = k_7395;


closureN_type c_73322;
object e_73489 [1];
c_73322.hdr.mark = gc_color_red;
 c_73322.hdr.grayed = 0;
c_73322.tag = closureN_tag;
 c_73322.fn = (function_type)__lambda_22;
c_73322.num_args = 1;
c_73322.num_elements = 1;
c_73322.elements = (object *)e_73489;
c_73322.elements[0] = k_7317_7354;

return_direct_with_clo1(data,(closure)&c_73268,__lambda_8,  &c_73322);; 
}

static void __lambda_22(void *data, object self_73151, int argc, object *args) /* object self_73151, object k_73111, object obj_7318_7355 */
 {
 object k_73111 = args[0]; object obj_7318_7355 = args[1];
  
closureN_type c_73324;
object e_73488 [2];
c_73324.hdr.mark = gc_color_red;
 c_73324.hdr.grayed = 0;
c_73324.tag = closureN_tag;
 c_73324.fn = (function_type)__lambda_23;
c_73324.num_args = 1;
c_73324.num_elements = 2;
c_73324.elements = (object *)e_73488;
c_73324.elements[0] = k_73111;
c_73324.elements[1] = ((closureN)self_73151)->elements[0];

return_direct_with_clo1(data,(closure)&c_73324,__lambda_23,  obj_7318_7355);; 
}

static void __lambda_23(void *data, object self_73152, int argc, object *args) /* object self_73152, object obj_7319_7356 */
 {
 object obj_7319_7356 = args[0];
  
closureN_type c_73326;
object e_73484 [2];
c_73326.hdr.mark = gc_color_red;
 c_73326.hdr.grayed = 0;
c_73326.tag = closureN_tag;
 c_73326.fn = (function_type)__lambda_55;
c_73326.num_args = 1;
c_73326.num_elements = 2;
c_73326.elements = (object *)e_73484;
c_73326.elements[0] = ((closureN)self_73152)->elements[0];
c_73326.elements[1] = ((closureN)self_73152)->elements[1];


pair_type local_73487; 
return_direct_with_clo1(data,(closure)&c_73326,__lambda_55,  set_cell_as_expr(&local_73487, obj_7319_7356));; 
}

static void __lambda_55(void *data, object self_73153, int argc, object *args) /* object self_73153, object obj_7319_7356 */
 {
 object obj_7319_7356 = args[0];
  
closureN_type c_73328;
object e_73482 [3];
c_73328.hdr.mark = gc_color_red;
 c_73328.hdr.grayed = 0;
c_73328.tag = closureN_tag;
 c_73328.fn = (function_type)__lambda_24;
c_73328.num_args = 1;
c_73328.num_elements = 3;
c_73328.elements = (object *)e_73482;
c_73328.elements[0] = ((closureN)self_73153)->elements[0];
c_73328.elements[1] = ((closureN)self_73153)->elements[1];
c_73328.elements[2] = obj_7319_7356;


make_utf8_string_with_len(c_73483, "Error: ", 7, 7);
return_closcall2(data,  __glo_display_scheme_write,  &c_73328, &c_73483);; 
}

static void __lambda_24(void *data, object self_73154, int argc, object *args) /* object self_73154, object r_73113 */
 {

  
closureN_type c_73330;
object e_73467 [1];
c_73330.hdr.mark = gc_color_red;
 c_73330.hdr.grayed = 0;
c_73330.tag = closureN_tag;
 c_73330.fn = (function_type)__lambda_25;
c_73330.num_args = 0;
c_73330.num_elements = 1;
c_73330.elements = (object *)e_73467;
c_73330.elements[0] = ((closureN)self_73154)->elements[2];


closureN_type c_73468;
object e_73481 [2];
c_73468.hdr.mark = gc_color_red;
 c_73468.hdr.grayed = 0;
c_73468.tag = closureN_tag;
 c_73468.fn = (function_type)__lambda_48;
c_73468.num_args = 1;
c_73468.num_elements = 2;
c_73468.elements = (object *)e_73481;
c_73468.elements[0] = ((closureN)self_73154)->elements[0];
c_73468.elements[1] = ((closureN)self_73154)->elements[1];

return_direct_with_clo1(data,(closure)&c_73330,__lambda_25,  &c_73468);; 
}

static void __lambda_48(void *data, object self_73155, int argc, object *args) /* object self_73155, object r_73114 */
 {

  
closureN_type c_73470;
object e_73480 [2];
c_73470.hdr.mark = gc_color_red;
 c_73470.hdr.grayed = 0;
c_73470.tag = closureN_tag;
 c_73470.fn = (function_type)__lambda_49;
c_73470.num_args = 1;
c_73470.num_elements = 2;
c_73470.elements = (object *)e_73480;
c_73470.elements[0] = ((closureN)self_73155)->elements[0];
c_73470.elements[1] = ((closureN)self_73155)->elements[1];

return_closcall1(data,  __glo_newline_scheme_base,  &c_73470);; 
}

static void __lambda_49(void *data, object self_73156, int argc, object *args) /* object self_73156, object r_73115 */
 {

  
closureN_type c_73472;
object e_73479 [2];
c_73472.hdr.mark = gc_color_red;
 c_73472.hdr.grayed = 0;
c_73472.tag = closureN_tag;
 c_73472.fn = (function_type)__lambda_50;
c_73472.num_args = 1;
c_73472.num_elements = 2;
c_73472.elements = (object *)e_73479;
c_73472.elements[0] = ((closureN)self_73156)->elements[0];
c_73472.elements[1] = ((closureN)self_73156)->elements[1];

return_closcall1(data,  __glo_ready_91for_91more_91input,  &c_73472);; 
}

static void __lambda_50(void *data, object self_73157, int argc, object *args) /* object self_73157, object r_73116 */
 {

  
closureN_type c_73474;
object e_73478 [2];
c_73474.hdr.mark = gc_color_red;
 c_73474.hdr.grayed = 0;
c_73474.tag = closureN_tag;
 c_73474.fn = (function_type)__lambda_51;
c_73474.num_args = 1;
c_73474.num_elements = 2;
c_73474.elements = (object *)e_73478;
c_73474.elements[0] = ((closureN)self_73157)->elements[0];
c_73474.elements[1] = ((closureN)self_73157)->elements[1];

return_closcall1(data,  __glo_loop,  &c_73474);; 
}

static void __lambda_51(void *data, object self_73158, int argc, object *args) /* object self_73158, object r_73112 */
 {
 object r_73112 = args[0];
  return_closcall2(data,  ((closureN)self_73158)->elements[1],  ((closureN)self_73158)->elements[0], r_73112);; 
}

static void __lambda_25(void *data, object self_73159, int argc, object *args) /* object self_73159, object k_73117 */
 {
 object k_73117 = args[0];
  
closureN_type c_73332;
object e_73463 [2];
c_73332.hdr.mark = gc_color_red;
 c_73332.hdr.grayed = 0;
c_73332.tag = closureN_tag;
 c_73332.fn = (function_type)__lambda_26;
c_73332.num_args = 1;
c_73332.num_elements = 2;
c_73332.elements = (object *)e_73463;
c_73332.elements[0] = k_73117;
c_73332.elements[1] = ((closureN)self_73159)->elements[0];



return_closcall2(data,  __glo_error_91object_127_scheme_base,  &c_73332, car(((closureN)self_73159)->elements[0]));; 
}

static void __lambda_26(void *data, object self_73160, int argc, object *args) /* object self_73160, object r_73118 */
 {
 object r_73118 = args[0];
  if( (boolean_f != r_73118) ){ 
  
closureN_type c_73334;
object e_73375 [2];
c_73334.hdr.mark = gc_color_red;
 c_73334.hdr.grayed = 0;
c_73334.tag = closureN_tag;
 c_73334.fn = (function_type)__lambda_27;
c_73334.num_args = 1;
c_73334.num_elements = 2;
c_73334.elements = (object *)e_73375;
c_73334.elements[0] = ((closureN)self_73160)->elements[0];
c_73334.elements[1] = ((closureN)self_73160)->elements[1];



return_closcall2(data,  __glo_error_91object_91message_scheme_base,  &c_73334, car(((closureN)self_73160)->elements[1]));
} else { 
  
closureN_type c_73380;
object e_73457 [2];
c_73380.hdr.mark = gc_color_red;
 c_73380.hdr.grayed = 0;
c_73380.tag = closureN_tag;
 c_73380.fn = (function_type)__lambda_36;
c_73380.num_args = 1;
c_73380.num_elements = 2;
c_73380.elements = (object *)e_73457;
c_73380.elements[0] = ((closureN)self_73160)->elements[0];
c_73380.elements[1] = ((closureN)self_73160)->elements[1];





return_direct_with_clo1(data,(closure)&c_73380,__lambda_36,  Cyc_is_pair(car(((closureN)self_73160)->elements[1])));}
;; 
}

static void __lambda_36(void *data, object self_73170, int argc, object *args) /* object self_73170, object r_73129 */
 {
 object r_73129 = args[0];
  if( (boolean_f != r_73129) ){ 
  
closureN_type c_73382;
object e_73434 [1];
c_73382.hdr.mark = gc_color_red;
 c_73382.hdr.grayed = 0;
c_73382.tag = closureN_tag;
 c_73382.fn = (function_type)__lambda_37;
c_73382.num_args = 0;
c_73382.num_elements = 1;
c_73382.elements = (object *)e_73434;
c_73382.elements[0] = ((closureN)self_73170)->elements[1];


closureN_type c_73435;
object e_73451 [2];
c_73435.hdr.mark = gc_color_red;
 c_73435.hdr.grayed = 0;
c_73435.tag = closureN_tag;
 c_73435.fn = (function_type)__lambda_44;
c_73435.num_args = 1;
c_73435.num_elements = 2;
c_73435.elements = (object *)e_73451;
c_73435.elements[0] = ((closureN)self_73170)->elements[0];
c_73435.elements[1] = ((closureN)self_73170)->elements[1];

return_direct_with_clo1(data,(closure)&c_73382,__lambda_37,  &c_73435);
} else { 
  

return_closcall2(data,  __glo_display_scheme_write,  ((closureN)self_73170)->elements[0], car(((closureN)self_73170)->elements[1]));}
;; 
}

static void __lambda_44(void *data, object self_73171, int argc, object *args) /* object self_73171, object r_73130 */
 {

  
closureN_type c_73437;
object e_73443 [2];
c_73437.hdr.mark = gc_color_red;
 c_73437.hdr.grayed = 0;
c_73437.tag = closureN_tag;
 c_73437.fn = (function_type)__lambda_45;
c_73437.num_args = 1;
c_73437.num_elements = 2;
c_73437.elements = (object *)e_73443;
c_73437.elements[0] = ((closureN)self_73171)->elements[0];
c_73437.elements[1] = ((closureN)self_73171)->elements[1];


mclosure0(c_73444, (function_type)__lambda_46);c_73444.num_args = 1;
return_direct_with_clo1(data,(closure)&c_73437,__lambda_45,  &c_73444);; 
}

static void __lambda_46(void *data, object self_73172, int argc, object *args) /* object self_73172, object k_73132, object o_7327_7358 */
 {
 object k_73132 = args[0]; object o_7327_7358 = args[1];
  
closureN_type c_73446;
object e_73450 [1];
c_73446.hdr.mark = gc_color_red;
 c_73446.hdr.grayed = 0;
c_73446.tag = closureN_tag;
 c_73446.fn = (function_type)__lambda_47;
c_73446.num_args = 1;
c_73446.num_elements = 1;
c_73446.elements = (object *)e_73450;
c_73446.elements[0] = k_73132;

return_closcall2(data,  __glo_write_scheme_write,  &c_73446, o_7327_7358);; 
}

static void __lambda_47(void *data, object self_73173, int argc, object *args) /* object self_73173, object r_73133 */
 {

  
make_utf8_string_with_len(c_73449, " ", 1, 1);
return_closcall2(data,  __glo_display_scheme_write,  ((closureN)self_73173)->elements[0], &c_73449);; 
}

static void __lambda_45(void *data, object self_73174, int argc, object *args) /* object self_73174, object r_73131 */
 {
 object r_73131 = args[0];
  

return_closcall3(data,  __glo_Cyc_91for_91each_91loop_911_scheme_base,  ((closureN)self_73174)->elements[0], r_73131, car(((closureN)self_73174)->elements[1]));; 
}

static void __lambda_37(void *data, object self_73175, int argc, object *args) /* object self_73175, object k_73134 */
 {
 object k_73134 = args[0];
  
closureN_type c_73384;
object e_73428 [2];
c_73384.hdr.mark = gc_color_red;
 c_73384.hdr.grayed = 0;
c_73384.tag = closureN_tag;
 c_73384.fn = (function_type)__lambda_38;
c_73384.num_args = 1;
c_73384.num_elements = 2;
c_73384.elements = (object *)e_73428;
c_73384.elements[0] = k_73134;
c_73384.elements[1] = ((closureN)self_73175)->elements[0];





return_direct_with_clo1(data,(closure)&c_73384,__lambda_38,  Cyc_car(data, car(((closureN)self_73175)->elements[0])));; 
}

static void __lambda_38(void *data, object self_73176, int argc, object *args) /* object self_73176, object r_73143 */
 {
 object r_73143 = args[0];
    
if( (boolean_f != Cyc_is_string(r_73143)) ){ 
  
closureN_type c_73388;
object e_73420 [2];
c_73388.hdr.mark = gc_color_red;
 c_73388.hdr.grayed = 0;
c_73388.tag = closureN_tag;
 c_73388.fn = (function_type)__lambda_39;
c_73388.num_args = 1;
c_73388.num_elements = 2;
c_73388.elements = (object *)e_73420;
c_73388.elements[0] = ((closureN)self_73176)->elements[0];
c_73388.elements[1] = ((closureN)self_73176)->elements[1];





return_direct_with_clo1(data,(closure)&c_73388,__lambda_39,  Cyc_car(data, car(((closureN)self_73176)->elements[1])));
} else { 
  return_closcall1(data,  ((closureN)self_73176)->elements[0],  Cyc_VOID);}
;; 
}

static void __lambda_39(void *data, object self_73177, int argc, object *args) /* object self_73177, object r_73142 */
 {
 object r_73142 = args[0];
  
closureN_type c_73390;
object e_73419 [2];
c_73390.hdr.mark = gc_color_red;
 c_73390.hdr.grayed = 0;
c_73390.tag = closureN_tag;
 c_73390.fn = (function_type)__lambda_40;
c_73390.num_args = 1;
c_73390.num_elements = 2;
c_73390.elements = (object *)e_73419;
c_73390.elements[0] = ((closureN)self_73177)->elements[0];
c_73390.elements[1] = ((closureN)self_73177)->elements[1];

return_closcall2(data,  __glo_display_scheme_write,  &c_73390, r_73142);; 
}

static void __lambda_40(void *data, object self_73178, int argc, object *args) /* object self_73178, object r_73136 */
 {

  
closureN_type c_73392;
object e_73403 [1];
c_73392.hdr.mark = gc_color_red;
 c_73392.hdr.grayed = 0;
c_73392.tag = closureN_tag;
 c_73392.fn = (function_type)__lambda_41;
c_73392.num_args = 0;
c_73392.num_elements = 1;
c_73392.elements = (object *)e_73403;
c_73392.elements[0] = ((closureN)self_73178)->elements[1];


closureN_type c_73404;
object e_73418 [2];
c_73404.hdr.mark = gc_color_red;
 c_73404.hdr.grayed = 0;
c_73404.tag = closureN_tag;
 c_73404.fn = (function_type)__lambda_42;
c_73404.num_args = 1;
c_73404.num_elements = 2;
c_73404.elements = (object *)e_73418;
c_73404.elements[0] = ((closureN)self_73178)->elements[0];
c_73404.elements[1] = ((closureN)self_73178)->elements[1];

return_direct_with_clo1(data,(closure)&c_73392,__lambda_41,  &c_73404);; 
}

static void __lambda_42(void *data, object self_73179, int argc, object *args) /* object self_73179, object r_73137 */
 {

  
closureN_type c_73406;
object e_73412 [2];
c_73406.hdr.mark = gc_color_red;
 c_73406.hdr.grayed = 0;
c_73406.tag = closureN_tag;
 c_73406.fn = (function_type)__lambda_43;
c_73406.num_args = 1;
c_73406.num_elements = 2;
c_73406.elements = (object *)e_73412;
c_73406.elements[0] = ((closureN)self_73179)->elements[0];
c_73406.elements[1] = ((closureN)self_73179)->elements[1];





return_direct_with_clo1(data,(closure)&c_73406,__lambda_43,  Cyc_cdr(data, car(((closureN)self_73179)->elements[1])));; 
}

static void __lambda_43(void *data, object self_73180, int argc, object *args) /* object self_73180, object r_73138 */
 {
 object r_73138 = args[0];
  

return_closcall1(data,  ((closureN)self_73180)->elements[0],  Cyc_set_cell(data, ((closureN)self_73180)->elements[1], r_73138));; 
}

static void __lambda_41(void *data, object self_73181, int argc, object *args) /* object self_73181, object k_73139 */
 {
 object k_73139 = args[0];
    
  
  
if( (boolean_f != Cyc_is_null(Cyc_cdr(data, car(((closureN)self_73181)->elements[0])))) ){ 
  return_closcall1(data,  k_73139,  Cyc_VOID);
} else { 
  
make_utf8_string_with_len(c_73402, ": ", 2, 2);
return_closcall2(data,  __glo_display_scheme_write,  k_73139, &c_73402);}
;; 
}

static void __lambda_27(void *data, object self_73161, int argc, object *args) /* object self_73161, object r_73128 */
 {
 object r_73128 = args[0];
  
closureN_type c_73336;
object e_73374 [2];
c_73336.hdr.mark = gc_color_red;
 c_73336.hdr.grayed = 0;
c_73336.tag = closureN_tag;
 c_73336.fn = (function_type)__lambda_28;
c_73336.num_args = 1;
c_73336.num_elements = 2;
c_73336.elements = (object *)e_73374;
c_73336.elements[0] = ((closureN)self_73161)->elements[0];
c_73336.elements[1] = ((closureN)self_73161)->elements[1];

return_closcall2(data,  __glo_display_scheme_write,  &c_73336, r_73128);; 
}

static void __lambda_28(void *data, object self_73162, int argc, object *args) /* object self_73162, object r_73119 */
 {

  
closureN_type c_73338;
object e_73352 [1];
c_73338.hdr.mark = gc_color_red;
 c_73338.hdr.grayed = 0;
c_73338.tag = closureN_tag;
 c_73338.fn = (function_type)__lambda_29;
c_73338.num_args = 0;
c_73338.num_elements = 1;
c_73338.elements = (object *)e_73352;
c_73338.elements[0] = ((closureN)self_73162)->elements[1];


closureN_type c_73353;
object e_73373 [2];
c_73353.hdr.mark = gc_color_red;
 c_73353.hdr.grayed = 0;
c_73353.tag = closureN_tag;
 c_73353.fn = (function_type)__lambda_31;
c_73353.num_args = 1;
c_73353.num_elements = 2;
c_73353.elements = (object *)e_73373;
c_73353.elements[0] = ((closureN)self_73162)->elements[0];
c_73353.elements[1] = ((closureN)self_73162)->elements[1];

return_direct_with_clo1(data,(closure)&c_73338,__lambda_29,  &c_73353);; 
}

static void __lambda_31(void *data, object self_73163, int argc, object *args) /* object self_73163, object r_73120 */
 {

  
closureN_type c_73355;
object e_73365 [2];
c_73355.hdr.mark = gc_color_red;
 c_73355.hdr.grayed = 0;
c_73355.tag = closureN_tag;
 c_73355.fn = (function_type)__lambda_32;
c_73355.num_args = 1;
c_73355.num_elements = 2;
c_73355.elements = (object *)e_73365;
c_73355.elements[0] = ((closureN)self_73163)->elements[0];
c_73355.elements[1] = ((closureN)self_73163)->elements[1];


mclosure0(c_73366, (function_type)__lambda_34);c_73366.num_args = 1;
return_direct_with_clo1(data,(closure)&c_73355,__lambda_32,  &c_73366);; 
}

static void __lambda_34(void *data, object self_73164, int argc, object *args) /* object self_73164, object k_73123, object o_7323_7357 */
 {
 object k_73123 = args[0]; object o_7323_7357 = args[1];
  
closureN_type c_73368;
object e_73372 [1];
c_73368.hdr.mark = gc_color_red;
 c_73368.hdr.grayed = 0;
c_73368.tag = closureN_tag;
 c_73368.fn = (function_type)__lambda_35;
c_73368.num_args = 1;
c_73368.num_elements = 1;
c_73368.elements = (object *)e_73372;
c_73368.elements[0] = k_73123;

return_closcall2(data,  __glo_write_scheme_write,  &c_73368, o_7323_7357);; 
}

static void __lambda_35(void *data, object self_73165, int argc, object *args) /* object self_73165, object r_73124 */
 {

  
make_utf8_string_with_len(c_73371, " ", 1, 1);
return_closcall2(data,  __glo_display_scheme_write,  ((closureN)self_73165)->elements[0], &c_73371);; 
}

static void __lambda_32(void *data, object self_73166, int argc, object *args) /* object self_73166, object r_73121 */
 {
 object r_73121 = args[0];
  
closureN_type c_73357;
object e_73361 [2];
c_73357.hdr.mark = gc_color_red;
 c_73357.hdr.grayed = 0;
c_73357.tag = closureN_tag;
 c_73357.fn = (function_type)__lambda_33;
c_73357.num_args = 1;
c_73357.num_elements = 2;
c_73357.elements = (object *)e_73361;
c_73357.elements[0] = ((closureN)self_73166)->elements[0];
c_73357.elements[1] = r_73121;



return_closcall2(data,  __glo_error_91object_91irritants_scheme_base,  &c_73357, car(((closureN)self_73166)->elements[1]));; 
}

static void __lambda_33(void *data, object self_73167, int argc, object *args) /* object self_73167, object r_73122 */
 {
 object r_73122 = args[0];
  return_closcall3(data,  __glo_Cyc_91for_91each_91loop_911_scheme_base,  ((closureN)self_73167)->elements[0], ((closureN)self_73167)->elements[1], r_73122);; 
}

static void __lambda_29(void *data, object self_73168, int argc, object *args) /* object self_73168, object k_73125 */
 {
 object k_73125 = args[0];
  
closureN_type c_73340;
object e_73348 [1];
c_73340.hdr.mark = gc_color_red;
 c_73340.hdr.grayed = 0;
c_73340.tag = closureN_tag;
 c_73340.fn = (function_type)__lambda_30;
c_73340.num_args = 1;
c_73340.num_elements = 1;
c_73340.elements = (object *)e_73348;
c_73340.elements[0] = k_73125;



return_closcall2(data,  __glo_error_91object_91irritants_scheme_base,  &c_73340, car(((closureN)self_73168)->elements[0]));; 
}

static void __lambda_30(void *data, object self_73169, int argc, object *args) /* object self_73169, object r_73127 */
 {
 object r_73127 = args[0];
    
if( (boolean_f != Cyc_is_null(r_73127)) ){ 
  return_closcall1(data,  ((closureN)self_73169)->elements[0],  Cyc_VOID);
} else { 
  
make_utf8_string_with_len(c_73347, ": ", 2, 2);
return_closcall2(data,  __glo_display_scheme_write,  ((closureN)self_73169)->elements[0], &c_73347);}
;; 
}

static void __lambda_8(void *data, object self_73182, int argc, object *args) /* object self_73182, object r_7396 */
 {
 object r_7396 = args[0];
  
closureN_type c_73270;
object e_73274 [2];
c_73270.hdr.mark = gc_color_red;
 c_73270.hdr.grayed = 0;
c_73270.tag = closureN_tag;
 c_73270.fn = (function_type)__lambda_9;
c_73270.num_args = 1;
c_73270.num_elements = 2;
c_73270.elements = (object *)e_73274;
c_73270.elements[0] = ((closureN)self_73182)->elements[0];
c_73270.elements[1] = r_7396;


mclosure0(c_73275, (function_type)__lambda_10);c_73275.num_args = 0;
return_direct_with_clo1(data,(closure)&c_73270,__lambda_9,  &c_73275);; 
}

static void __lambda_10(void *data, object self_73183, int argc, object *args) /* object self_73183, object k_7398 */
 {
 object k_7398 = args[0];
  
closureN_type c_73277;
object e_73320 [1];
c_73277.hdr.mark = gc_color_red;
 c_73277.hdr.grayed = 0;
c_73277.tag = closureN_tag;
 c_73277.fn = (function_type)__lambda_11;
c_73277.num_args = 1;
c_73277.num_elements = 1;
c_73277.elements = (object *)e_73320;
c_73277.elements[0] = k_7398;

return_closcall1(data,  __glo_get_91input,  &c_73277);; 
}

static void __lambda_11(void *data, object self_73184, int argc, object *args) /* object self_73184, object str_7329_7359 */
 {
 object str_7329_7359 = args[0];
  
closureN_type c_73279;
object e_73311 [1];
c_73279.hdr.mark = gc_color_red;
 c_73279.hdr.grayed = 0;
c_73279.tag = closureN_tag;
 c_73279.fn = (function_type)__lambda_12;
c_73279.num_args = 0;
c_73279.num_elements = 1;
c_73279.elements = (object *)e_73311;
c_73279.elements[0] = str_7329_7359;


closureN_type c_73312;
object e_73319 [1];
c_73312.hdr.mark = gc_color_red;
 c_73312.hdr.grayed = 0;
c_73312.tag = closureN_tag;
 c_73312.fn = (function_type)__lambda_20;
c_73312.num_args = 1;
c_73312.num_elements = 1;
c_73312.elements = (object *)e_73319;
c_73312.elements[0] = ((closureN)self_73184)->elements[0];

return_direct_with_clo1(data,(closure)&c_73279,__lambda_12,  &c_73312);; 
}

static void __lambda_20(void *data, object self_73185, int argc, object *args) /* object self_73185, object r_7399 */
 {

  
closureN_type c_73314;
object e_73317 [1];
c_73314.hdr.mark = gc_color_red;
 c_73314.hdr.grayed = 0;
c_73314.tag = closureN_tag;
 c_73314.fn = (function_type)__lambda_21;
c_73314.num_args = 1;
c_73314.num_elements = 1;
c_73314.elements = (object *)e_73317;
c_73314.elements[0] = ((closureN)self_73185)->elements[0];


make_double(c_73318, 0.1);
return_closcall2(data,  __glo_thread_91sleep_67_srfi_18,  &c_73314, &c_73318);; 
}

static void __lambda_21(void *data, object self_73186, int argc, object *args) /* object self_73186, object r_73100 */
 {

  return_closcall1(data,  __glo_loop,  ((closureN)self_73186)->elements[0]);; 
}

static void __lambda_12(void *data, object self_73187, int argc, object *args) /* object self_73187, object k_73102 */
 {
 object k_73102 = args[0];
  if( (boolean_f != ((closureN)self_73187)->elements[0]) ){ 
  
closureN_type c_73282;
object e_73308 [1];
c_73282.hdr.mark = gc_color_red;
 c_73282.hdr.grayed = 0;
c_73282.tag = closureN_tag;
 c_73282.fn = (function_type)__lambda_13;
c_73282.num_args = 1;
c_73282.num_elements = 1;
c_73282.elements = (object *)e_73308;
c_73282.elements[0] = k_73102;

return_closcall2(data,  __glo_open_91input_91string_scheme_base,  &c_73282, ((closureN)self_73187)->elements[0]);
} else { 
  return_closcall1(data,  k_73102,  Cyc_VOID);}
;; 
}

static void __lambda_13(void *data, object self_73188, int argc, object *args) /* object self_73188, object fp_7332_7360 */
 {
 object fp_7332_7360 = args[0];
  
closureN_type c_73284;
object e_73307 [2];
c_73284.hdr.mark = gc_color_red;
 c_73284.hdr.grayed = 0;
c_73284.tag = closureN_tag;
 c_73284.fn = (function_type)__lambda_14;
c_73284.num_args = 1;
c_73284.num_elements = 2;
c_73284.elements = (object *)e_73307;
c_73284.elements[0] = fp_7332_7360;
c_73284.elements[1] = ((closureN)self_73188)->elements[0];

return_closcall2(data,  __glo_read_91all_scheme_read,  &c_73284, fp_7332_7360);; 
}

static void __lambda_14(void *data, object self_73189, int argc, object *args) /* object self_73189, object sexp_91lis_7335_7361 */
 {
 object sexp_91lis_7335_7361 = args[0];
  
closureN_type c_73286;
object e_73297 [3];
c_73286.hdr.mark = gc_color_red;
 c_73286.hdr.grayed = 0;
c_73286.tag = closureN_tag;
 c_73286.fn = (function_type)__lambda_15;
c_73286.num_args = 1;
c_73286.num_elements = 3;
c_73286.elements = (object *)e_73297;
c_73286.elements[0] = ((closureN)self_73189)->elements[0];
c_73286.elements[1] = ((closureN)self_73189)->elements[1];
c_73286.elements[2] = sexp_91lis_7335_7361;


mclosure0(c_73298, (function_type)__lambda_17);c_73298.num_args = 1;
return_direct_with_clo1(data,(closure)&c_73286,__lambda_15,  &c_73298);; 
}

static void __lambda_17(void *data, object self_73190, int argc, object *args) /* object self_73190, object k_73108, object sexp_7337_7362 */
 {
 object k_73108 = args[0]; object sexp_7337_7362 = args[1];
  
closureN_type c_73300;
object e_73306 [1];
c_73300.hdr.mark = gc_color_red;
 c_73300.hdr.grayed = 0;
c_73300.tag = closureN_tag;
 c_73300.fn = (function_type)__lambda_18;
c_73300.num_args = 1;
c_73300.num_elements = 1;
c_73300.elements = (object *)e_73306;
c_73300.elements[0] = k_73108;

return_closcall2(data,  __glo_eval_scheme_eval,  &c_73300, sexp_7337_7362);; 
}

static void __lambda_18(void *data, object self_73191, int argc, object *args) /* object self_73191, object obj_7338_7363 */
 {
 object obj_7338_7363 = args[0];
  
closureN_type c_73302;
object e_73305 [1];
c_73302.hdr.mark = gc_color_red;
 c_73302.hdr.grayed = 0;
c_73302.tag = closureN_tag;
 c_73302.fn = (function_type)__lambda_19;
c_73302.num_args = 1;
c_73302.num_elements = 1;
c_73302.elements = (object *)e_73305;
c_73302.elements[0] = ((closureN)self_73191)->elements[0];

return_closcall2(data,  __glo_write_scheme_write,  &c_73302, obj_7338_7363);; 
}

static void __lambda_19(void *data, object self_73192, int argc, object *args) /* object self_73192, object r_73110 */
 {

  return_closcall1(data,  __glo_newline_scheme_base,  ((closureN)self_73192)->elements[0]);; 
}

static void __lambda_15(void *data, object self_73193, int argc, object *args) /* object self_73193, object r_73107 */
 {
 object r_73107 = args[0];
  
closureN_type c_73288;
object e_73295 [2];
c_73288.hdr.mark = gc_color_red;
 c_73288.hdr.grayed = 0;
c_73288.tag = closureN_tag;
 c_73288.fn = (function_type)__lambda_16;
c_73288.num_args = 1;
c_73288.num_elements = 2;
c_73288.elements = (object *)e_73295;
c_73288.elements[0] = ((closureN)self_73193)->elements[0];
c_73288.elements[1] = ((closureN)self_73193)->elements[1];

return_closcall3(data,  __glo_Cyc_91for_91each_91loop_911_scheme_base,  &c_73288, r_73107, ((closureN)self_73193)->elements[2]);; 
}

static void __lambda_16(void *data, object self_73194, int argc, object *args) /* object self_73194, object r_73106 */
 {

  
  Cyc_io_close_port(data, ((closureN)self_73194)->elements[0]);return_closcall1(data,  __glo_ready_91for_91more_91input,  ((closureN)self_73194)->elements[1]);;; 
}

static void __lambda_9(void *data, object self_73195, int argc, object *args) /* object self_73195, object r_7397 */
 {
 object r_7397 = args[0];
  return_closcall3(data,  __glo_with_91exception_91handler_scheme_base,  ((closureN)self_73195)->elements[0], ((closureN)self_73195)->elements[1], r_7397);; 
}

static void __lambda_6(void *data, object self_73196, int argc, object *args) /* object self_73196, object r_7394 */
 {
 object r_7394 = args[0];
  return_closcall2(data,  __glo_call_95cc_scheme_base,  ((closureN)self_73196)->elements[0], r_7394);; 
}

static void __lambda_58(void *data, object _, int argc, object *args) { object k = args[0]; 
    object cmd = args[1];
    MAIN_THREAD_ASYNC_EM_ASM({
      helpLink(UTF8ToString($0));
    }, symbol_desc(cmd));
    return_closcall1(data, k, boolean_f);
   }
static void __lambda_57(void *data, object _, int argc, object *args) { object k = args[0]; 
    MAIN_THREAD_ASYNC_EM_ASM(
      readyForNextCommand();
    );
    return_closcall1(data, k, boolean_f);
   }
static void __lambda_56(void *data, object _, int argc, object *args) { object k = args[0]; 
    /* TODO: use mutex to lock glo_sexp */
    char *s = glo_sexp;
    glo_sexp = NULL;
    /* TODO: unlock */
  
    if (s != NULL) {
      make_utf8_string(data, str, s);
      free(s);
      return_closcall1(data, k, &str); 
    } else {
      return_closcall1(data, k, boolean_f);
    }  }
static void __lambda_2(void *data, object _, int argc, object *args) /* closure _,object k_7383, object opts_7311_7353_raw, ... */
 {
object k_7383 = args[0];
load_varargs(opts_7311_7353, args, 1, argc - 1);
  object r_7384;
  Cyc_st_add(data, "src/terminal.scm:%help");
  
if( (boolean_f != Cyc_is_pair(opts_7311_7353)) ){ 
  
  
  r_7384 = Cyc_is_symbol(Cyc_car(data, opts_7311_7353));
} else { 
  r_7384 = boolean_f;}
;if( (boolean_f != r_7384) ){ 
  
closureN_type c_73236;
object e_73242 [1];
c_73236.hdr.mark = gc_color_red;
 c_73236.hdr.grayed = 0;
c_73236.tag = closureN_tag;
 c_73236.fn = (function_type)__lambda_3;
c_73236.num_args = 1;
c_73236.num_elements = 1;
c_73236.elements = (object *)e_73242;
c_73236.elements[0] = k_7383;



return_closcall2(data,  __glo_display_91help_91for_91cmd,  &c_73236, Cyc_car(data, opts_7311_7353));
} else { 
  
closureN_type c_73246;
object e_73249 [1];
c_73246.hdr.mark = gc_color_red;
 c_73246.hdr.grayed = 0;
c_73246.tag = closureN_tag;
 c_73246.fn = (function_type)__lambda_4;
c_73246.num_args = 1;
c_73246.num_elements = 1;
c_73246.elements = (object *)e_73249;
c_73246.elements[0] = k_7383;


make_utf8_string_with_len(c_73253, "Type (help) to see this menu.\nType (help object) to find API documentation for object.\nType Shift-Enter to enter multi-line input.\n\nCyclone\nUser Manual: ", 153, 153);

make_utf8_string_with_len(c_73254, "/docs/User-Manual\nAPI Documentation: ", 37, 37);

make_utf8_string_with_len(c_73255, "/docs/API\nReport a Bug: https://github.com/justinethier/cyclone/issues\n\nOther Resources\nR7RS Scheme Language Specification: ", 124, 124);

make_utf8_string_with_len(c_73256, "/docs/r7rs.pdf\n\n", 16, 16);

object c_73252 = Cyc_string_append(data,(closure)&c_73246,7,&c_73253, __glo__85site_91url_85, &c_73254, __glo__85site_91url_85, &c_73255, __glo__85site_91url_85, &c_73256);
return_closcall1(data,(closure)&c_73246,  c_73252);}
;; 
}

static void __lambda_4(void *data, object self_73149, int argc, object *args) /* object self_73149, object r_7387 */
 {
 object r_7387 = args[0];
  return_closcall2(data,  __glo_display_scheme_write,  ((closureN)self_73149)->elements[0], r_7387);; 
}

static void __lambda_3(void *data, object self_73148, int argc, object *args) /* object self_73148, object r_7385 */
 {

  
complex_num_type local_73241; 
return_closcall1(data,  ((closureN)self_73148)->elements[0],  ((inline_function_type)
                   ((closure)__glo_void_191_191inline_191_191_scheme_base)->fn)(data,&local_73241));; 
}

static void __lambda_1(void *data, object _, int argc, object *args) /* closure _,object k_7368, object expr_731_7349, object rename_732_7350, object compare_733_7351 */
 {
object k_7368 = args[0]; object expr_731_7349 = args[1];
  Cyc_st_add(data, "src/terminal.scm:help");
  
  
if( (boolean_f != Cyc_num_fast_eq_op(data, Cyc_length(data, expr_731_7349), obj_int2obj(1))) ){ 
  
pair_type local_73209; 
return_closcall1(data,  k_7368,  set_pair_as_expr(&local_73209, quote__75help, NULL));
} else { 
  
pair_type local_73213; 

pair_type local_73216; 

pair_type local_73219; 

pair_type local_73222; 


return_closcall1(data,  k_7368,  set_pair_as_expr(&local_73213, quote__75help, set_pair_as_expr(&local_73216, set_pair_as_expr(&local_73219, quote_quote, set_pair_as_expr(&local_73222, Cyc_cadr(data, expr_731_7349), NULL)), NULL)));}
;; 
}

static void c_entry_pt_first_lambda(void *data, object clo, int argc, object *args);
extern void c_schemecyclonecommon_entry_pt(void *data, object clo, int argc, object* args);
extern void c_schemebase_entry_pt(void *data, object clo, int argc, object* args);
extern void c_srfi18_entry_pt(void *data, object clo, int argc, object* args);
extern void c_schemefile_entry_pt(void *data, object clo, int argc, object* args);
extern void c_scheme_char_entry_pt(void *data, object clo, int argc, object* args);
extern void c_srfi69_entry_pt(void *data, object clo, int argc, object* args);
extern void c_schemewrite_entry_pt(void *data, object clo, int argc, object* args);
extern void c_schemecyclonehashset_entry_pt(void *data, object clo, int argc, object* args);
extern void c_schemecycloneprimitives_entry_pt(void *data, object clo, int argc, object* args);
extern void c_schemeprocess_91context_entry_pt(void *data, object clo, int argc, object* args);
extern void c_schemeread_entry_pt(void *data, object clo, int argc, object* args);
extern void c_schemecycloneutil_entry_pt(void *data, object clo, int argc, object* args);
extern void c_schemecyclonelibraries_entry_pt(void *data, object clo, int argc, object* args);
extern void c_schemeeval_entry_pt(void *data, object clo, int argc, object* args);
static void c_entry_pt(void *data, object clo, int argc, object *args) { 
Cyc_set_globals_changed((gc_thread_data *)data);
  quote_quote = find_or_add_symbol("quote");
  quote__75help = find_or_add_symbol("%help");

  add_global("__glo_loop", (object *) &__glo_loop);
  add_global("__glo_display_91help_91for_91cmd", (object *) &__glo_display_91help_91for_91cmd);
  add_global("__glo_ready_91for_91more_91input", (object *) &__glo_ready_91for_91more_91input);
  add_global("__glo_get_91input", (object *) &__glo_get_91input);
  add_global("__glo__75help", (object *) &__glo__75help);
  add_global("__glo_help", (object *) &__glo_help);
  add_global("__glo__85site_91url_85", (object *) &__glo__85site_91url_85);
  mclosure0(c_73260, (function_type)__lambda_5);c_73260.num_args = 0; 
  __glo_loop = &c_73260; 
  mclosure0(c_73259, (function_type)__lambda_58);c_73259.num_args = 0; 
  __glo_display_91help_91for_91cmd = &c_73259; 
  mclosure0(c_73258, (function_type)__lambda_57);c_73258.num_args = 0; 
  __glo_ready_91for_91more_91input = &c_73258; 
  mclosure0(c_73257, (function_type)__lambda_56);c_73257.num_args = 0; 
  __glo_get_91input = &c_73257; 
  mclosure0(c_73225, (function_type)__lambda_2);c_73225.num_args = 0; 
  __glo__75help = &c_73225; 
  mmacro(c_73201, (function_type)__lambda_1);c_73201.num_args = 3; 
  __glo_help = &c_73201; 
  make_utf8_string_with_len(c_73200, "http://justinethier.github.io/cyclone", 37, 37); 
  __glo__85site_91url_85 = &c_73200; 

  make_cvar(cvar_73500, (object *)&__glo_loop);make_pair(pair_73501, find_or_add_symbol("loop"), &cvar_73500);
  make_cvar(cvar_73502, (object *)&__glo_display_91help_91for_91cmd);make_pair(pair_73503, find_or_add_symbol("display-help-for-cmd"), &cvar_73502);
  make_cvar(cvar_73504, (object *)&__glo_ready_91for_91more_91input);make_pair(pair_73505, find_or_add_symbol("ready-for-more-input"), &cvar_73504);
  make_cvar(cvar_73506, (object *)&__glo_get_91input);make_pair(pair_73507, find_or_add_symbol("get-input"), &cvar_73506);
  make_cvar(cvar_73508, (object *)&__glo__75help);make_pair(pair_73509, find_or_add_symbol("%help"), &cvar_73508);
  make_cvar(cvar_73510, (object *)&__glo_help);make_pair(pair_73511, find_or_add_symbol("help"), &cvar_73510);
  make_cvar(cvar_73512, (object *)&__glo__85site_91url_85);make_pair(pair_73513, find_or_add_symbol("*site-url*"), &cvar_73512);
make_pair(c_73520, &pair_73501,Cyc_global_variables);
make_pair(c_73519, &pair_73503, &c_73520);
make_pair(c_73518, &pair_73505, &c_73519);
make_pair(c_73517, &pair_73507, &c_73518);
make_pair(c_73516, &pair_73509, &c_73517);
make_pair(c_73515, &pair_73511, &c_73516);
make_pair(c_73514, &pair_73513, &c_73515);
Cyc_global_variables = &c_73514;
mclosure1(c_done, c_entry_pt_first_lambda, &c_done);
mclosure1(c_73521, c_schemeeval_entry_pt, &c_done);
mclosure1(c_73522, c_schemecyclonelibraries_entry_pt, &c_73521);
mclosure1(c_73523, c_schemecycloneutil_entry_pt, &c_73522);
mclosure1(c_73524, c_schemeread_entry_pt, &c_73523);
mclosure1(c_73525, c_schemeprocess_91context_entry_pt, &c_73524);
mclosure1(c_73526, c_schemecycloneprimitives_entry_pt, &c_73525);
mclosure1(c_73527, c_schemecyclonehashset_entry_pt, &c_73526);
mclosure1(c_73528, c_schemewrite_entry_pt, &c_73527);
mclosure1(c_73529, c_srfi69_entry_pt, &c_73528);
mclosure1(c_73530, c_scheme_char_entry_pt, &c_73529);
mclosure1(c_73531, c_schemefile_entry_pt, &c_73530);
mclosure1(c_73532, c_srfi18_entry_pt, &c_73531);
mclosure1(c_73533, c_schemebase_entry_pt, &c_73532);
mclosure1(c_73534, c_schemecyclonecommon_entry_pt, &c_73533);
 object buf[1]; buf[0] = &c_73534; (c_73534.fn)(data, &c_73534, 1, buf);
}
static void c_entry_pt_first_lambda(void *data, object clo, int argc, object *args) {
  
    
    
    
    
    
    
    
mclosure0(c_73491, (function_type)__lambda_52);c_73491.num_args = 1;
return_closcall1(data,  __glo__75help,  &c_73491);
;
}
int main(int argc, char **argv, char **envp)
{gc_thread_data *thd;
 long stack_size = global_stack_size = STACK_SIZE;
 long heap_size = global_heap_size = HEAP_SIZE;
 init_polyfills();
 mclosure0(clos_halt,&Cyc_halt);  // Halt if final closure is reached
 mclosure0(entry_pt,&c_entry_pt); // First function to execute
 _cyc_argc = argc;
 _cyc_argv = argv;
 set_env_variables(envp);
 gc_initialize();
 thd = malloc(sizeof(gc_thread_data));
 gc_thread_data_init(thd, 0, (char *) &stack_size, stack_size);
 thd->gc_cont = &entry_pt;
 thd->gc_args[0] = &clos_halt;
 thd->gc_num_args = 1;
 thd->thread_id = pthread_self();
 gc_add_mutator(thd);
 Cyc_heap_init(heap_size);
 thd->thread_state = CYC_THREAD_STATE_RUNNABLE;
 Cyc_start_trampoline(thd);
 return 0;}
