/**
 ** This file was automatically generated by the Cyclone scheme compiler
 ** http://justinethier.github.io/cyclone/
 **
 ** (c) 2014-2021 Justin Ethier
 ** Version 0.28.0 
 **
 **/

#define closcall1(td, clo, buf) \
if (obj_is_not_closure(clo)) { \
   Cyc_apply(td, clo, 1, buf ); \
} else { \
   ((clo)->fn)(td, clo, 1, buf); \
;\
}
#define return_closcall1(td, clo,a1) { \
 char top; \
 object buf[1]; buf[0] = a1;\
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     GC(td, clo, buf, 1); \
     return; \
 } else {\
     closcall1(td, (closure) (clo), buf); \
     return;\
 } \
}

#define continue_or_gc1(td, clo,a1) { \
 char *top = alloca(sizeof(char)); \
 if (stack_overflow(top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[1]; buf[0] = a1;\
     GC(td, clo, buf, 1); \
     return; \
 } else {\
     continue;\
 } \
}

#define return_direct1(td, _fn,a1) { \
 char top; \
 object buf[1]; buf[0] = a1; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     mclosure0(c1, (function_type) _fn); \
     GC(td, &c1, buf, 1); \
     return; \
 } else { \
     (_fn)(td, (closure)_fn, 1, buf); \
 }}

#define return_direct_with_clo1(td, clo, _fn,a1) { \
 char top; \
 object buf[1]; buf[0] = a1;\
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     GC(td, clo, buf, 1); \
     return; \
 } else { \
     (_fn)(td, (closure)(clo), 1, buf); \
 }}

#define closcall2(td, clo, buf) \
if (obj_is_not_closure(clo)) { \
   Cyc_apply(td, clo, 2, buf ); \
} else { \
   ((clo)->fn)(td, clo, 2, buf); \
;\
}
#define return_closcall2(td, clo,a1,a2) { \
 char top; \
 object buf[2]; buf[0] = a1;buf[1] = a2;\
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     GC(td, clo, buf, 2); \
     return; \
 } else {\
     closcall2(td, (closure) (clo), buf); \
     return;\
 } \
}

#define continue_or_gc2(td, clo,a1,a2) { \
 char *top = alloca(sizeof(char)); \
 if (stack_overflow(top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[2]; buf[0] = a1;buf[1] = a2;\
     GC(td, clo, buf, 2); \
     return; \
 } else {\
     continue;\
 } \
}

#define return_direct2(td, _fn,a1,a2) { \
 char top; \
 object buf[2]; buf[0] = a1;buf[1] = a2; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     mclosure0(c1, (function_type) _fn); \
     GC(td, &c1, buf, 2); \
     return; \
 } else { \
     (_fn)(td, (closure)_fn, 2, buf); \
 }}

#define return_direct_with_clo2(td, clo, _fn,a1,a2) { \
 char top; \
 object buf[2]; buf[0] = a1;buf[1] = a2;\
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     GC(td, clo, buf, 2); \
     return; \
 } else { \
     (_fn)(td, (closure)(clo), 2, buf); \
 }}

#define closcall3(td, clo, buf) \
if (obj_is_not_closure(clo)) { \
   Cyc_apply(td, clo, 3, buf ); \
} else { \
   ((clo)->fn)(td, clo, 3, buf); \
;\
}
#define return_closcall3(td, clo,a1,a2,a3) { \
 char top; \
 object buf[3]; buf[0] = a1;buf[1] = a2;buf[2] = a3;\
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     GC(td, clo, buf, 3); \
     return; \
 } else {\
     closcall3(td, (closure) (clo), buf); \
     return;\
 } \
}

#define continue_or_gc3(td, clo,a1,a2,a3) { \
 char *top = alloca(sizeof(char)); \
 if (stack_overflow(top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[3]; buf[0] = a1;buf[1] = a2;buf[2] = a3;\
     GC(td, clo, buf, 3); \
     return; \
 } else {\
     continue;\
 } \
}

#define return_direct3(td, _fn,a1,a2,a3) { \
 char top; \
 object buf[3]; buf[0] = a1;buf[1] = a2;buf[2] = a3; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     mclosure0(c1, (function_type) _fn); \
     GC(td, &c1, buf, 3); \
     return; \
 } else { \
     (_fn)(td, (closure)_fn, 3, buf); \
 }}

#define return_direct_with_clo3(td, clo, _fn,a1,a2,a3) { \
 char top; \
 object buf[3]; buf[0] = a1;buf[1] = a2;buf[2] = a3;\
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     GC(td, clo, buf, 3); \
     return; \
 } else { \
     (_fn)(td, (closure)(clo), 3, buf); \
 }}

#include <emscripten.h>
#include "ck-polyfill.h"
#include "terminal.h"
#include "cyclone/types.h"
object __glo_loop = NULL;
object __glo_display_91help_91for_91cmd = NULL;
object __glo_ready_91for_91more_91input = NULL;
object __glo_get_91input = NULL;
object __glo__75help = NULL;
object __glo_help = NULL;
object __glo__85site_91url_85 = NULL;
extern object __glo_member_scheme_base;
extern object __glo_assoc_scheme_base;
extern object __glo_cons_91source_scheme_base;
extern object __glo_syntax_91rules_scheme_base;
extern object __glo_letrec_85_scheme_base;
extern object __glo_guard_scheme_base;
extern object __glo_guard_91aux_scheme_base;
extern object __glo_define_91record_91type_scheme_base;
extern object __glo_record_127_scheme_base;
extern object __glo_is_91a_127_scheme_base;
extern object __glo_register_91simple_91type_scheme_base;
extern object __glo_make_91type_91predicate_scheme_base;
extern object __glo_make_91constructor_scheme_base;
extern object __glo_make_91constructor_95args_scheme_base;
extern object __glo_make_91getter_scheme_base;
extern object __glo_make_91setter_scheme_base;
extern object __glo_slot_91ref_scheme_base;
extern object __glo_slot_91set_67_scheme_base;
extern object __glo_type_91slot_91offset_scheme_base;
extern object __glo_make_91record_91marker_scheme_base;
extern object __glo_receive_scheme_base;
extern object __glo_abs_scheme_base;
extern object __glo_max_scheme_base;
extern object __glo_min_scheme_base;
extern object __glo_modulo_scheme_base;
extern object __glo_floor_91remainder_scheme_base;
extern object __glo_even_127_scheme_base;
extern object __glo_exact_91integer_127_scheme_base;
extern object __glo_exact_91integer_91sqrt_scheme_base;
extern object __glo_exact_127_scheme_base;
extern object __glo_inexact_127_scheme_base;
extern object __glo_odd_127_scheme_base;
extern object __glo_complex_127_scheme_base;
extern object __glo_rational_127_scheme_base;
extern object __glo_bignum_127_scheme_base;
extern object __glo_gcd_scheme_base;
extern object __glo_lcm_scheme_base;
extern object __glo_quotient_scheme_base;
extern object __glo_remainder_scheme_base;
extern object __glo_truncate_91quotient_scheme_base;
extern object __glo_truncate_91remainder_scheme_base;
extern object __glo_truncate_95_scheme_base;
extern object __glo_floor_91quotient_scheme_base;
extern object __glo_floor_91remainder_scheme_base;
extern object __glo_floor_95_scheme_base;
extern object __glo_square_scheme_base;
extern object __glo_expt_scheme_base;
extern object __glo_call_91with_91current_91continuation_scheme_base;
extern object __glo_call_95cc_scheme_base;
extern object __glo_call_91with_91values_scheme_base;
extern object __glo_dynamic_91wind_scheme_base;
extern object __glo_values_scheme_base;
extern object __glo_char_123_127_scheme_base;
extern object __glo_char_121_127_scheme_base;
extern object __glo_char_125_127_scheme_base;
extern object __glo_char_121_123_127_scheme_base;
extern object __glo_char_125_123_127_scheme_base;
extern object __glo_string_123_127_scheme_base;
extern object __glo_string_121_127_scheme_base;
extern object __glo_string_121_123_127_scheme_base;
extern object __glo_string_125_127_scheme_base;
extern object __glo_string_125_123_127_scheme_base;
extern object __glo_fast_91string_123_127_scheme_base;
extern object __glo_fast_91string_121_127_scheme_base;
extern object __glo_fast_91string_121_123_127_scheme_base;
extern object __glo_fast_91string_125_127_scheme_base;
extern object __glo_fast_91string_125_123_127_scheme_base;
extern object __glo_foldl_scheme_base;
extern object __glo_foldr_scheme_base;
extern object __glo_not_scheme_base;
extern object __glo_list_127_scheme_base;
extern object __glo_zero_127_scheme_base;
extern object __glo_positive_127_scheme_base;
extern object __glo_negative_127_scheme_base;
extern object __glo_append_scheme_base;
extern object __glo__list_scheme_base;
extern object __glo_make_91list_scheme_base;
extern object __glo_list_91copy_scheme_base;
extern object __glo_map_scheme_base;
extern object __glo_Cyc_91map_91loop_911_scheme_base;
extern object __glo_Cyc_91map_91loop_912_scheme_base;
extern object __glo_Cyc_91for_91each_91loop_911_scheme_base;
extern object __glo_Cyc_91for_91each_91loop_912_scheme_base;
extern object __glo_for_91each_scheme_base;
extern object __glo_list_91tail_scheme_base;
extern object __glo_list_91ref_scheme_base;
extern object __glo_list_91set_67_scheme_base;
extern object __glo_reverse_scheme_base;
extern object __glo_boolean_123_127_scheme_base;
extern object __glo_symbol_123_127_scheme_base;
extern object __glo_Cyc_91obj_123_127_scheme_base;
extern object __glo_vector_scheme_base;
extern object __glo_vector_91append_scheme_base;
extern object __glo_vector_91copy_scheme_base;
extern object __glo_vector_91copy_67_scheme_base;
extern object __glo_vector_91fill_67_scheme_base;
extern object __glo_vector_91_125list_scheme_base;
extern object __glo_vector_91_125string_scheme_base;
extern object __glo_vector_91map_scheme_base;
extern object __glo_vector_91for_91each_scheme_base;
extern object __glo_make_91string_scheme_base;
extern object __glo_string_scheme_base;
extern object __glo_string_91copy_scheme_base;
extern object __glo_string_91copy_67_scheme_base;
extern object __glo_string_91fill_67_scheme_base;
extern object __glo_string_91_125list_scheme_base;
extern object __glo_string_91_125vector_scheme_base;
extern object __glo_string_91map_scheme_base;
extern object __glo_string_91for_91each_scheme_base;
extern object __glo_make_91parameter_scheme_base;
extern object __glo_current_91output_91port_scheme_base;
extern object __glo_current_91input_91port_scheme_base;
extern object __glo_current_91error_91port_scheme_base;
extern object __glo_call_91with_91port_scheme_base;
extern object __glo_error_91object_127_scheme_base;
extern object __glo_error_91object_91message_scheme_base;
extern object __glo_error_91object_91irritants_scheme_base;
extern object __glo_error_95loc_scheme_base;
extern object __glo_error_scheme_base;
extern object __glo_raise_scheme_base;
extern object __glo_raise_91continuable_scheme_base;
extern object __glo_with_91handler_scheme_base;
extern object __glo_with_91exception_91handler_scheme_base;
extern object __glo_Cyc_91add_91exception_91handler_scheme_base;
extern object __glo_Cyc_91remove_91exception_91handler_scheme_base;
extern object __glo_newline_scheme_base;
extern object __glo_write_91char_scheme_base;
extern object __glo_write_91string_scheme_base;
extern object __glo_write_91string_911_scheme_base;
extern object __glo_write_91string_912_scheme_base;
extern object __glo_flush_91output_91port_scheme_base;
extern object __glo_peek_91char_scheme_base;
extern object __glo_read_91char_scheme_base;
extern object __glo_read_91line_scheme_base;
extern object __glo_read_91string_scheme_base;
extern object __glo_input_91port_127_scheme_base;
extern object __glo_output_91port_127_scheme_base;
extern object __glo_input_91port_91open_127_scheme_base;
extern object __glo_output_91port_91open_127_scheme_base;
extern object __glo_get_91output_91string_scheme_base;
extern object __glo_open_91output_91string_scheme_base;
extern object __glo_open_91input_91string_scheme_base;
extern object __glo_get_91output_91bytevector_scheme_base;
extern object __glo_open_91input_91bytevector_scheme_base;
extern object __glo_open_91output_91bytevector_scheme_base;
extern object __glo_features_scheme_base;
extern object __glo_Cyc_91add_91feature_67_scheme_base;
extern object __glo_Cyc_91version_scheme_base;
extern object __glo_any_scheme_base;
extern object __glo_every_scheme_base;
extern object __glo_and_scheme_base;
extern object __glo_or_scheme_base;
extern object __glo_let_scheme_base;
extern object __glo_let_85_scheme_base;
extern object __glo_letrec_scheme_base;
extern object __glo_let_85_91values_scheme_base;
extern object __glo_let_91values_scheme_base;
extern object __glo_define_91values_scheme_base;
extern object __glo_begin_scheme_base;
extern object __glo__case_scheme_base;
extern object __glo_cond_scheme_base;
extern object __glo_cond_91expand_scheme_base;
extern object __glo__do_scheme_base;
extern object __glo_when_scheme_base;
extern object __glo_unless_scheme_base;
extern object __glo_quasiquote_scheme_base;
extern object __glo_floor_scheme_base;
extern object __glo_ceiling_scheme_base;
extern object __glo_truncate_scheme_base;
extern object __glo_round_scheme_base;
extern object __glo_exact_scheme_base;
extern object __glo_inexact_scheme_base;
extern object __glo_eof_91object_scheme_base;
extern object __glo__void_scheme_base;
extern object __glo_syntax_91error_scheme_base;
extern object __glo_bytevector_91copy_scheme_base;
extern object __glo_bytevector_91copy_67_scheme_base;
extern object __glo_utf8_91_125string_scheme_base;
extern object __glo_string_91_125utf8_scheme_base;
extern object __glo_denominator_scheme_base;
extern object __glo_numerator_scheme_base;
extern object __glo_parameterize_scheme_base;
extern object __glo_read_91bytevector_scheme_base;
extern object __glo_read_91bytevector_67_scheme_base;
extern object __glo_write_91bytevector_scheme_base;
extern object __glo_peek_91u8_scheme_base;
extern object __glo_read_91u8_scheme_base;
extern object __glo_write_91u8_scheme_base;
extern object __glo_binary_91port_127_scheme_base;
extern object __glo_textual_91port_127_scheme_base;
extern object __glo_read_scheme_read;
extern object __glo_read_91all_scheme_read;
extern object __glo_read_91all_95source_scheme_read;
extern object __glo_include_scheme_read;
extern object __glo_include_91ci_scheme_read;
extern object __glo_display_scheme_write;
extern object __glo_write_scheme_write;
extern object __glo_write_91shared_scheme_write;
extern object __glo_write_91simple_scheme_write;
extern object __glo_eval_scheme_eval;
extern object __glo_eval_91from_91c_scheme_eval;
extern object __glo_create_91environment_scheme_eval;
extern object __glo_setup_91environment_scheme_eval;
extern object __glo__75import_scheme_eval;
extern object __glo_imported_127_scheme_eval;
extern object __glo__75set_91import_91dirs_67_scheme_eval;
extern object __glo_import_91shared_91object_scheme_eval;
extern object __glo__85defined_91macros_85_scheme_eval;
extern object __glo_get_91macros_scheme_eval;
extern object __glo_macro_117macro_127_scheme_eval;
extern object __glo_macro_117expand_scheme_eval;
extern object __glo_macro_117add_67_scheme_eval;
extern object __glo_macro_117cleanup_scheme_eval;
extern object __glo_macro_117load_91env_67_scheme_eval;
extern object __glo_macro_117get_91env_scheme_eval;
extern object __glo_macro_117get_91defined_91macros_scheme_eval;
extern object __glo_expand_scheme_eval;
extern object __glo_expand_91lambda_91body_scheme_eval;
extern object __glo_thread_127_srfi_18;
extern object __glo_make_91thread_srfi_18;
extern object __glo_thread_91name_srfi_18;
extern object __glo_thread_91specific_srfi_18;
extern object __glo_thread_91specific_91set_67_srfi_18;
extern object __glo_thread_91start_67_srfi_18;
extern object __glo_thread_91sleep_67_srfi_18;
extern object __glo_thread_91yield_67_srfi_18;
extern object __glo_thread_91terminate_67_srfi_18;
extern object __glo_current_91thread_srfi_18;
extern object __glo_current_91thread_91data_srfi_18;
extern object __glo_thread_91join_67_srfi_18;
extern object __glo_mutex_127_srfi_18;
extern object __glo_make_91mutex_srfi_18;
extern object __glo_mutex_91lock_67_srfi_18;
extern object __glo_mutex_91unlock_67_srfi_18;
extern object __glo_condition_91variable_127_srfi_18;
extern object __glo_make_91condition_91variable_srfi_18;
extern object __glo_condition_91variable_91wait_67_srfi_18;
extern object __glo_condition_91variable_91signal_67_srfi_18;
extern object __glo_condition_91variable_91broadcast_67_srfi_18;
extern object __glo__91_125heap_srfi_18;
extern object __glo_Cyc_91minor_91gc_srfi_18;
extern object __glo_fast_91string_123_127_191_191inline_191_191_scheme_base;
extern object __glo_fast_91string_121_127_191_191inline_191_191_scheme_base;
extern object __glo_fast_91string_121_123_127_191_191inline_191_191_scheme_base;
extern object __glo_fast_91string_125_127_191_191inline_191_191_scheme_base;
extern object __glo_fast_91string_125_123_127_191_191inline_191_191_scheme_base;
extern object __glo__75write_91bytevector_191_191inline_191_191_scheme_base;
extern object __glo_not_191_191inline_191_191_scheme_base;
extern object __glo_list_127_191_191inline_191_191_scheme_base;
extern object __glo_zero_127_191_191inline_191_191_scheme_base;
extern object __glo_positive_127_191_191inline_191_191_scheme_base;
extern object __glo_negative_127_191_191inline_191_191_scheme_base;
extern object __glo_floor_191_191inline_191_191_scheme_base;
extern object __glo_ceiling_191_191inline_191_191_scheme_base;
extern object __glo_truncate_191_191inline_191_191_scheme_base;
extern object __glo_round_191_191inline_191_191_scheme_base;
extern object __glo_inexact_191_191inline_191_191_scheme_base;
extern object __glo_sqrt_191_191inline_191_191_scheme_base;
extern object __glo_exact_91integer_127_191_191inline_191_191_scheme_base;
extern object __glo_exact_127_191_191inline_191_191_scheme_base;
extern object __glo_complex_127_191_191inline_191_191_scheme_base;
extern object __glo_denominator_191_191inline_191_191_scheme_base;
extern object __glo_numerator_191_191inline_191_191_scheme_base;
extern object __glo_quotient_191_191inline_191_191_scheme_base;
extern object __glo_square_191_191inline_191_191_scheme_base;
extern object __glo_eof_91object_191_191inline_191_191_scheme_base;
extern object __glo_void_191_191inline_191_191_scheme_base;
extern object __glo_make_91record_91marker_191_191inline_191_191_scheme_base;
extern object __glo_Cyc_91opaque_91eq_127_191_191inline_191_191_scheme_read;
extern object __glo_Cyc_91opaque_91unsafe_91eq_127_191_191inline_191_191_scheme_read;
extern object __glo_Cyc_91opaque_91unsafe_91string_127_191_191inline_191_191_scheme_read;
extern object __glo_variable_127_191_191inline_191_191_scheme_eval;
extern object __glo_assignment_91variable_191_191inline_191_191_scheme_eval;
extern object __glo_assignment_91value_191_191inline_191_191_scheme_eval;
extern object __glo_definition_91variable_191_191inline_191_191_scheme_eval;
extern object __glo_lambda_91parameters_191_191inline_191_191_scheme_eval;
extern object __glo_lambda_91body_191_191inline_191_191_scheme_eval;
extern object __glo_if_91predicate_191_191inline_191_191_scheme_eval;
extern object __glo_if_91consequent_191_191inline_191_191_scheme_eval;
extern object __glo_if_91alternative_191_191inline_191_191_scheme_eval;
extern object __glo_application_127_191_191inline_191_191_scheme_eval;
extern object __glo_operator_191_191inline_191_191_scheme_eval;
extern object __glo_operands_191_191inline_191_191_scheme_eval;
extern object __glo_procedure_91parameters_191_191inline_191_191_scheme_eval;
extern object __glo_procedure_91body_191_191inline_191_191_scheme_eval;
extern object __glo_procedure_91environment_191_191inline_191_191_scheme_eval;
extern object __glo_primitive_91implementation_191_191inline_191_191_scheme_eval;
extern object __glo_macro_117macro_127_191_191inline_191_191_scheme_eval;
#include "cyclone/runtime.h"
#include "cyclone/runtime-main.h"
defsymbol(quote);
defsymbol(_75help);
static void __lambda_52(void *data, object clo, int argc, object *args) ;/*object self_73197, object r_73145*/
static void __lambda_53(void *data, object clo, int argc, object *args) ;/*object self_73198, object r_73146*/
static void __lambda_54(void *data, object clo, int argc, object *args) ;/*object self_73199, object r_73147*/
static void __lambda_5(void *data, object clo, int argc, object *args) ;/*closure _,object k_7393*/
static void __lambda_7(void *data, object clo, int argc, object *args) ;/*object self_73150, object k_7395, object k_7317_7354*/
static void __lambda_22(void *data, object clo, int argc, object *args) ;/*object self_73151, object k_73111, object obj_7318_7355*/
static void __lambda_23(void *data, object clo, int argc, object *args) ;/*object self_73152, object obj_7319_7356*/
static void __lambda_55(void *data, object clo, int argc, object *args) ;/*object self_73153, object obj_7319_7356*/
static void __lambda_24(void *data, object clo, int argc, object *args) ;/*object self_73154, object r_73113*/
static void __lambda_48(void *data, object clo, int argc, object *args) ;/*object self_73155, object r_73114*/
static void __lambda_49(void *data, object clo, int argc, object *args) ;/*object self_73156, object r_73115*/
static void __lambda_50(void *data, object clo, int argc, object *args) ;/*object self_73157, object r_73116*/
static void __lambda_51(void *data, object clo, int argc, object *args) ;/*object self_73158, object r_73112*/
static void __lambda_25(void *data, object clo, int argc, object *args) ;/*object self_73159, object k_73117*/
static void __lambda_26(void *data, object clo, int argc, object *args) ;/*object self_73160, object r_73118*/
static void __lambda_36(void *data, object clo, int argc, object *args) ;/*object self_73170, object r_73129*/
static void __lambda_44(void *data, object clo, int argc, object *args) ;/*object self_73171, object r_73130*/
static void __lambda_46(void *data, object clo, int argc, object *args) ;/*object self_73172, object k_73132, object o_7327_7358*/
static void __lambda_47(void *data, object clo, int argc, object *args) ;/*object self_73173, object r_73133*/
static void __lambda_45(void *data, object clo, int argc, object *args) ;/*object self_73174, object r_73131*/
static void __lambda_37(void *data, object clo, int argc, object *args) ;/*object self_73175, object k_73134*/
static void __lambda_38(void *data, object clo, int argc, object *args) ;/*object self_73176, object r_73143*/
static void __lambda_39(void *data, object clo, int argc, object *args) ;/*object self_73177, object r_73142*/
static void __lambda_40(void *data, object clo, int argc, object *args) ;/*object self_73178, object r_73136*/
static void __lambda_42(void *data, object clo, int argc, object *args) ;/*object self_73179, object r_73137*/
static void __lambda_43(void *data, object clo, int argc, object *args) ;/*object self_73180, object r_73138*/
static void __lambda_41(void *data, object clo, int argc, object *args) ;/*object self_73181, object k_73139*/
static void __lambda_27(void *data, object clo, int argc, object *args) ;/*object self_73161, object r_73128*/
static void __lambda_28(void *data, object clo, int argc, object *args) ;/*object self_73162, object r_73119*/
static void __lambda_31(void *data, object clo, int argc, object *args) ;/*object self_73163, object r_73120*/
static void __lambda_34(void *data, object clo, int argc, object *args) ;/*object self_73164, object k_73123, object o_7323_7357*/
static void __lambda_35(void *data, object clo, int argc, object *args) ;/*object self_73165, object r_73124*/
static void __lambda_32(void *data, object clo, int argc, object *args) ;/*object self_73166, object r_73121*/
static void __lambda_33(void *data, object clo, int argc, object *args) ;/*object self_73167, object r_73122*/
static void __lambda_29(void *data, object clo, int argc, object *args) ;/*object self_73168, object k_73125*/
static void __lambda_30(void *data, object clo, int argc, object *args) ;/*object self_73169, object r_73127*/
static void __lambda_8(void *data, object clo, int argc, object *args) ;/*object self_73182, object r_7396*/
static void __lambda_10(void *data, object clo, int argc, object *args) ;/*object self_73183, object k_7398*/
static void __lambda_11(void *data, object clo, int argc, object *args) ;/*object self_73184, object str_7329_7359*/
static void __lambda_20(void *data, object clo, int argc, object *args) ;/*object self_73185, object r_7399*/
static void __lambda_21(void *data, object clo, int argc, object *args) ;/*object self_73186, object r_73100*/
static void __lambda_12(void *data, object clo, int argc, object *args) ;/*object self_73187, object k_73102*/
static void __lambda_13(void *data, object clo, int argc, object *args) ;/*object self_73188, object fp_7332_7360*/
static void __lambda_14(void *data, object clo, int argc, object *args) ;/*object self_73189, object sexp_91lis_7335_7361*/
static void __lambda_17(void *data, object clo, int argc, object *args) ;/*object self_73190, object k_73108, object sexp_7337_7362*/
static void __lambda_18(void *data, object clo, int argc, object *args) ;/*object self_73191, object obj_7338_7363*/
static void __lambda_19(void *data, object clo, int argc, object *args) ;/*object self_73192, object r_73110*/
static void __lambda_15(void *data, object clo, int argc, object *args) ;/*object self_73193, object r_73107*/
static void __lambda_16(void *data, object clo, int argc, object *args) ;/*object self_73194, object r_73106*/
static void __lambda_9(void *data, object clo, int argc, object *args) ;/*object self_73195, object r_7397*/
static void __lambda_6(void *data, object clo, int argc, object *args) ;/*object self_73196, object r_7394*/
static void __lambda_58(void *data, object clo, int argc, object *args) ;/*(void *data, object _, int argc, object *args)*/
static void __lambda_57(void *data, object clo, int argc, object *args) ;/*(void *data, object _, int argc, object *args)*/
static void __lambda_56(void *data, object clo, int argc, object *args) ;/*(void *data, object _, int argc, object *args)*/
static void __lambda_2(void *data, object clo, int argc, object *args) ;/*closure _,object k_7383, object opts_7311_7353_raw, ...*/
static void __lambda_4(void *data, object clo, int argc, object *args) ;/*object self_73149, object r_7387*/
static void __lambda_3(void *data, object clo, int argc, object *args) ;/*object self_73148, object r_7385*/
static void __lambda_1(void *data, object clo, int argc, object *args) ;/*closure _,object k_7368, object expr_731_7349, object rename_732_7350, object compare_733_7351*/

static void __lambda_52(void *data, object self_73197, int argc, object *args) /* object self_73197, object r_73145 */
 {

  
mclosure0(c_73494, (function_type)__lambda_53);c_73494.num_args = 1;
return_closcall1(data,  __glo_ready_91for_91more_91input,  &c_73494);; 
}

static void __lambda_53(void *data, object self_73198, int argc, object *args) /* object self_73198, object r_73146 */
 {

  
mclosure0(c_73496, (function_type)__lambda_54);c_73496.num_args = 1;
return_closcall1(data,  __glo_loop,  &c_73496);; 
}

static void __lambda_54(void *data, object self_73199, int argc, object *args) /* object self_73199, object r_73147 */
 {

  
  
  __halt(__halt(obj_int2obj(0)));; 
}

static void __lambda_5(void *data, object _, int argc, object *args) /* closure _,object k_7393 */
 {
object k_7393 = args[0];
  Cyc_st_add(data, "src/terminal.scm:loop");

closureN_type c_73263;
object e_73266 [1];
c_73263.hdr.mark = gc_color_red;
 c_73263.hdr.grayed = 0;
c_73263.tag = closureN_tag;
 c_73263.fn = (function_type)__lambda_6;
c_73263.num_args = 1;
c_73263.num_elements = 1;
c_73263.elements = (object *)e_73266;
c_73263.elements[0] = k_7393;


mclosure0(c_73267, (function_type)__lambda_7);c_73267.num_args = 1;
return_direct_with_clo1(data,(closure)&c_73263,__lambda_6,  &c_73267);; 
}

static void __lambda_7(void *data, object self_73150, int argc, object *args) /* object self_73150, object k_7395, object k_7317_7354 */
 {
 object k_7395 = args[0]; object k_7317_7354 = args[1];
  
closureN_type c_73269;
object e_73322 [1];
c_73269.hdr.mark = gc_color_red;
 c_73269.hdr.grayed = 0;
c_73269.tag = closureN_tag;
 c_73269.fn = (function_type)__lambda_8;
c_73269.num_args = 1;
c_73269.num_elements = 1;
c_73269.elements = (object *)e_73322;
c_73269.elements[0] = k_7395;


closureN_type c_73323;
object e_73490 [1];
c_73323.hdr.mark = gc_color_red;
 c_73323.hdr.grayed = 0;
c_73323.tag = closureN_tag;
 c_73323.fn = (function_type)__lambda_22;
c_73323.num_args = 1;
c_73323.num_elements = 1;
c_73323.elements = (object *)e_73490;
c_73323.elements[0] = k_7317_7354;

return_direct_with_clo1(data,(closure)&c_73269,__lambda_8,  &c_73323);; 
}

static void __lambda_22(void *data, object self_73151, int argc, object *args) /* object self_73151, object k_73111, object obj_7318_7355 */
 {
 object k_73111 = args[0]; object obj_7318_7355 = args[1];
  
closureN_type c_73325;
object e_73489 [2];
c_73325.hdr.mark = gc_color_red;
 c_73325.hdr.grayed = 0;
c_73325.tag = closureN_tag;
 c_73325.fn = (function_type)__lambda_23;
c_73325.num_args = 1;
c_73325.num_elements = 2;
c_73325.elements = (object *)e_73489;
c_73325.elements[0] = k_73111;
c_73325.elements[1] = ((closureN)self_73151)->elements[0];

return_direct_with_clo1(data,(closure)&c_73325,__lambda_23,  obj_7318_7355);; 
}

static void __lambda_23(void *data, object self_73152, int argc, object *args) /* object self_73152, object obj_7319_7356 */
 {
 object obj_7319_7356 = args[0];
  
closureN_type c_73327;
object e_73485 [2];
c_73327.hdr.mark = gc_color_red;
 c_73327.hdr.grayed = 0;
c_73327.tag = closureN_tag;
 c_73327.fn = (function_type)__lambda_55;
c_73327.num_args = 1;
c_73327.num_elements = 2;
c_73327.elements = (object *)e_73485;
c_73327.elements[0] = ((closureN)self_73152)->elements[0];
c_73327.elements[1] = ((closureN)self_73152)->elements[1];


pair_type local_73488; 
return_direct_with_clo1(data,(closure)&c_73327,__lambda_55,  set_cell_as_expr(&local_73488, obj_7319_7356));; 
}

static void __lambda_55(void *data, object self_73153, int argc, object *args) /* object self_73153, object obj_7319_7356 */
 {
 object obj_7319_7356 = args[0];
  
closureN_type c_73329;
object e_73483 [3];
c_73329.hdr.mark = gc_color_red;
 c_73329.hdr.grayed = 0;
c_73329.tag = closureN_tag;
 c_73329.fn = (function_type)__lambda_24;
c_73329.num_args = 1;
c_73329.num_elements = 3;
c_73329.elements = (object *)e_73483;
c_73329.elements[0] = ((closureN)self_73153)->elements[0];
c_73329.elements[1] = ((closureN)self_73153)->elements[1];
c_73329.elements[2] = obj_7319_7356;


make_utf8_string_with_len(c_73484, "Error: ", 7, 7);
return_closcall2(data,  __glo_display_scheme_write,  &c_73329, &c_73484);; 
}

static void __lambda_24(void *data, object self_73154, int argc, object *args) /* object self_73154, object r_73113 */
 {

  
closureN_type c_73331;
object e_73468 [1];
c_73331.hdr.mark = gc_color_red;
 c_73331.hdr.grayed = 0;
c_73331.tag = closureN_tag;
 c_73331.fn = (function_type)__lambda_25;
c_73331.num_args = 0;
c_73331.num_elements = 1;
c_73331.elements = (object *)e_73468;
c_73331.elements[0] = ((closureN)self_73154)->elements[2];


closureN_type c_73469;
object e_73482 [2];
c_73469.hdr.mark = gc_color_red;
 c_73469.hdr.grayed = 0;
c_73469.tag = closureN_tag;
 c_73469.fn = (function_type)__lambda_48;
c_73469.num_args = 1;
c_73469.num_elements = 2;
c_73469.elements = (object *)e_73482;
c_73469.elements[0] = ((closureN)self_73154)->elements[0];
c_73469.elements[1] = ((closureN)self_73154)->elements[1];

return_direct_with_clo1(data,(closure)&c_73331,__lambda_25,  &c_73469);; 
}

static void __lambda_48(void *data, object self_73155, int argc, object *args) /* object self_73155, object r_73114 */
 {

  
closureN_type c_73471;
object e_73481 [2];
c_73471.hdr.mark = gc_color_red;
 c_73471.hdr.grayed = 0;
c_73471.tag = closureN_tag;
 c_73471.fn = (function_type)__lambda_49;
c_73471.num_args = 1;
c_73471.num_elements = 2;
c_73471.elements = (object *)e_73481;
c_73471.elements[0] = ((closureN)self_73155)->elements[0];
c_73471.elements[1] = ((closureN)self_73155)->elements[1];

return_closcall1(data,  __glo_newline_scheme_base,  &c_73471);; 
}

static void __lambda_49(void *data, object self_73156, int argc, object *args) /* object self_73156, object r_73115 */
 {

  
closureN_type c_73473;
object e_73480 [2];
c_73473.hdr.mark = gc_color_red;
 c_73473.hdr.grayed = 0;
c_73473.tag = closureN_tag;
 c_73473.fn = (function_type)__lambda_50;
c_73473.num_args = 1;
c_73473.num_elements = 2;
c_73473.elements = (object *)e_73480;
c_73473.elements[0] = ((closureN)self_73156)->elements[0];
c_73473.elements[1] = ((closureN)self_73156)->elements[1];

return_closcall1(data,  __glo_ready_91for_91more_91input,  &c_73473);; 
}

static void __lambda_50(void *data, object self_73157, int argc, object *args) /* object self_73157, object r_73116 */
 {

  
closureN_type c_73475;
object e_73479 [2];
c_73475.hdr.mark = gc_color_red;
 c_73475.hdr.grayed = 0;
c_73475.tag = closureN_tag;
 c_73475.fn = (function_type)__lambda_51;
c_73475.num_args = 1;
c_73475.num_elements = 2;
c_73475.elements = (object *)e_73479;
c_73475.elements[0] = ((closureN)self_73157)->elements[0];
c_73475.elements[1] = ((closureN)self_73157)->elements[1];

return_closcall1(data,  __glo_loop,  &c_73475);; 
}

static void __lambda_51(void *data, object self_73158, int argc, object *args) /* object self_73158, object r_73112 */
 {
 object r_73112 = args[0];
  return_closcall2(data,  ((closureN)self_73158)->elements[1],  ((closureN)self_73158)->elements[0], r_73112);; 
}

static void __lambda_25(void *data, object self_73159, int argc, object *args) /* object self_73159, object k_73117 */
 {
 object k_73117 = args[0];
  
closureN_type c_73333;
object e_73464 [2];
c_73333.hdr.mark = gc_color_red;
 c_73333.hdr.grayed = 0;
c_73333.tag = closureN_tag;
 c_73333.fn = (function_type)__lambda_26;
c_73333.num_args = 1;
c_73333.num_elements = 2;
c_73333.elements = (object *)e_73464;
c_73333.elements[0] = k_73117;
c_73333.elements[1] = ((closureN)self_73159)->elements[0];



return_closcall2(data,  __glo_error_91object_127_scheme_base,  &c_73333, car(((closureN)self_73159)->elements[0]));; 
}

static void __lambda_26(void *data, object self_73160, int argc, object *args) /* object self_73160, object r_73118 */
 {
 object r_73118 = args[0];
  if( (boolean_f != r_73118) ){ 
  
closureN_type c_73335;
object e_73376 [2];
c_73335.hdr.mark = gc_color_red;
 c_73335.hdr.grayed = 0;
c_73335.tag = closureN_tag;
 c_73335.fn = (function_type)__lambda_27;
c_73335.num_args = 1;
c_73335.num_elements = 2;
c_73335.elements = (object *)e_73376;
c_73335.elements[0] = ((closureN)self_73160)->elements[0];
c_73335.elements[1] = ((closureN)self_73160)->elements[1];



return_closcall2(data,  __glo_error_91object_91message_scheme_base,  &c_73335, car(((closureN)self_73160)->elements[1]));
} else { 
  
closureN_type c_73381;
object e_73458 [2];
c_73381.hdr.mark = gc_color_red;
 c_73381.hdr.grayed = 0;
c_73381.tag = closureN_tag;
 c_73381.fn = (function_type)__lambda_36;
c_73381.num_args = 1;
c_73381.num_elements = 2;
c_73381.elements = (object *)e_73458;
c_73381.elements[0] = ((closureN)self_73160)->elements[0];
c_73381.elements[1] = ((closureN)self_73160)->elements[1];





return_direct_with_clo1(data,(closure)&c_73381,__lambda_36,  Cyc_is_pair(car(((closureN)self_73160)->elements[1])));}
;; 
}

static void __lambda_36(void *data, object self_73170, int argc, object *args) /* object self_73170, object r_73129 */
 {
 object r_73129 = args[0];
  if( (boolean_f != r_73129) ){ 
  
closureN_type c_73383;
object e_73435 [1];
c_73383.hdr.mark = gc_color_red;
 c_73383.hdr.grayed = 0;
c_73383.tag = closureN_tag;
 c_73383.fn = (function_type)__lambda_37;
c_73383.num_args = 0;
c_73383.num_elements = 1;
c_73383.elements = (object *)e_73435;
c_73383.elements[0] = ((closureN)self_73170)->elements[1];


closureN_type c_73436;
object e_73452 [2];
c_73436.hdr.mark = gc_color_red;
 c_73436.hdr.grayed = 0;
c_73436.tag = closureN_tag;
 c_73436.fn = (function_type)__lambda_44;
c_73436.num_args = 1;
c_73436.num_elements = 2;
c_73436.elements = (object *)e_73452;
c_73436.elements[0] = ((closureN)self_73170)->elements[0];
c_73436.elements[1] = ((closureN)self_73170)->elements[1];

return_direct_with_clo1(data,(closure)&c_73383,__lambda_37,  &c_73436);
} else { 
  

return_closcall2(data,  __glo_display_scheme_write,  ((closureN)self_73170)->elements[0], car(((closureN)self_73170)->elements[1]));}
;; 
}

static void __lambda_44(void *data, object self_73171, int argc, object *args) /* object self_73171, object r_73130 */
 {

  
closureN_type c_73438;
object e_73444 [2];
c_73438.hdr.mark = gc_color_red;
 c_73438.hdr.grayed = 0;
c_73438.tag = closureN_tag;
 c_73438.fn = (function_type)__lambda_45;
c_73438.num_args = 1;
c_73438.num_elements = 2;
c_73438.elements = (object *)e_73444;
c_73438.elements[0] = ((closureN)self_73171)->elements[0];
c_73438.elements[1] = ((closureN)self_73171)->elements[1];


mclosure0(c_73445, (function_type)__lambda_46);c_73445.num_args = 1;
return_direct_with_clo1(data,(closure)&c_73438,__lambda_45,  &c_73445);; 
}

static void __lambda_46(void *data, object self_73172, int argc, object *args) /* object self_73172, object k_73132, object o_7327_7358 */
 {
 object k_73132 = args[0]; object o_7327_7358 = args[1];
  
closureN_type c_73447;
object e_73451 [1];
c_73447.hdr.mark = gc_color_red;
 c_73447.hdr.grayed = 0;
c_73447.tag = closureN_tag;
 c_73447.fn = (function_type)__lambda_47;
c_73447.num_args = 1;
c_73447.num_elements = 1;
c_73447.elements = (object *)e_73451;
c_73447.elements[0] = k_73132;

return_closcall2(data,  __glo_write_scheme_write,  &c_73447, o_7327_7358);; 
}

static void __lambda_47(void *data, object self_73173, int argc, object *args) /* object self_73173, object r_73133 */
 {

  
make_utf8_string_with_len(c_73450, " ", 1, 1);
return_closcall2(data,  __glo_display_scheme_write,  ((closureN)self_73173)->elements[0], &c_73450);; 
}

static void __lambda_45(void *data, object self_73174, int argc, object *args) /* object self_73174, object r_73131 */
 {
 object r_73131 = args[0];
  

return_closcall3(data,  __glo_Cyc_91for_91each_91loop_911_scheme_base,  ((closureN)self_73174)->elements[0], r_73131, car(((closureN)self_73174)->elements[1]));; 
}

static void __lambda_37(void *data, object self_73175, int argc, object *args) /* object self_73175, object k_73134 */
 {
 object k_73134 = args[0];
  
closureN_type c_73385;
object e_73429 [2];
c_73385.hdr.mark = gc_color_red;
 c_73385.hdr.grayed = 0;
c_73385.tag = closureN_tag;
 c_73385.fn = (function_type)__lambda_38;
c_73385.num_args = 1;
c_73385.num_elements = 2;
c_73385.elements = (object *)e_73429;
c_73385.elements[0] = k_73134;
c_73385.elements[1] = ((closureN)self_73175)->elements[0];





return_direct_with_clo1(data,(closure)&c_73385,__lambda_38,  Cyc_car(data, car(((closureN)self_73175)->elements[0])));; 
}

static void __lambda_38(void *data, object self_73176, int argc, object *args) /* object self_73176, object r_73143 */
 {
 object r_73143 = args[0];
    
if( (boolean_f != Cyc_is_string(r_73143)) ){ 
  
closureN_type c_73389;
object e_73421 [2];
c_73389.hdr.mark = gc_color_red;
 c_73389.hdr.grayed = 0;
c_73389.tag = closureN_tag;
 c_73389.fn = (function_type)__lambda_39;
c_73389.num_args = 1;
c_73389.num_elements = 2;
c_73389.elements = (object *)e_73421;
c_73389.elements[0] = ((closureN)self_73176)->elements[0];
c_73389.elements[1] = ((closureN)self_73176)->elements[1];





return_direct_with_clo1(data,(closure)&c_73389,__lambda_39,  Cyc_car(data, car(((closureN)self_73176)->elements[1])));
} else { 
  return_closcall1(data,  ((closureN)self_73176)->elements[0],  Cyc_VOID);}
;; 
}

static void __lambda_39(void *data, object self_73177, int argc, object *args) /* object self_73177, object r_73142 */
 {
 object r_73142 = args[0];
  
closureN_type c_73391;
object e_73420 [2];
c_73391.hdr.mark = gc_color_red;
 c_73391.hdr.grayed = 0;
c_73391.tag = closureN_tag;
 c_73391.fn = (function_type)__lambda_40;
c_73391.num_args = 1;
c_73391.num_elements = 2;
c_73391.elements = (object *)e_73420;
c_73391.elements[0] = ((closureN)self_73177)->elements[0];
c_73391.elements[1] = ((closureN)self_73177)->elements[1];

return_closcall2(data,  __glo_display_scheme_write,  &c_73391, r_73142);; 
}

static void __lambda_40(void *data, object self_73178, int argc, object *args) /* object self_73178, object r_73136 */
 {

  
closureN_type c_73393;
object e_73404 [1];
c_73393.hdr.mark = gc_color_red;
 c_73393.hdr.grayed = 0;
c_73393.tag = closureN_tag;
 c_73393.fn = (function_type)__lambda_41;
c_73393.num_args = 0;
c_73393.num_elements = 1;
c_73393.elements = (object *)e_73404;
c_73393.elements[0] = ((closureN)self_73178)->elements[1];


closureN_type c_73405;
object e_73419 [2];
c_73405.hdr.mark = gc_color_red;
 c_73405.hdr.grayed = 0;
c_73405.tag = closureN_tag;
 c_73405.fn = (function_type)__lambda_42;
c_73405.num_args = 1;
c_73405.num_elements = 2;
c_73405.elements = (object *)e_73419;
c_73405.elements[0] = ((closureN)self_73178)->elements[0];
c_73405.elements[1] = ((closureN)self_73178)->elements[1];

return_direct_with_clo1(data,(closure)&c_73393,__lambda_41,  &c_73405);; 
}

static void __lambda_42(void *data, object self_73179, int argc, object *args) /* object self_73179, object r_73137 */
 {

  
closureN_type c_73407;
object e_73413 [2];
c_73407.hdr.mark = gc_color_red;
 c_73407.hdr.grayed = 0;
c_73407.tag = closureN_tag;
 c_73407.fn = (function_type)__lambda_43;
c_73407.num_args = 1;
c_73407.num_elements = 2;
c_73407.elements = (object *)e_73413;
c_73407.elements[0] = ((closureN)self_73179)->elements[0];
c_73407.elements[1] = ((closureN)self_73179)->elements[1];





return_direct_with_clo1(data,(closure)&c_73407,__lambda_43,  Cyc_cdr(data, car(((closureN)self_73179)->elements[1])));; 
}

static void __lambda_43(void *data, object self_73180, int argc, object *args) /* object self_73180, object r_73138 */
 {
 object r_73138 = args[0];
  

return_closcall1(data,  ((closureN)self_73180)->elements[0],  Cyc_set_cell(data, ((closureN)self_73180)->elements[1], r_73138));; 
}

static void __lambda_41(void *data, object self_73181, int argc, object *args) /* object self_73181, object k_73139 */
 {
 object k_73139 = args[0];
    
  
  
if( (boolean_f != Cyc_is_null(Cyc_cdr(data, car(((closureN)self_73181)->elements[0])))) ){ 
  return_closcall1(data,  k_73139,  Cyc_VOID);
} else { 
  
make_utf8_string_with_len(c_73403, ": ", 2, 2);
return_closcall2(data,  __glo_display_scheme_write,  k_73139, &c_73403);}
;; 
}

static void __lambda_27(void *data, object self_73161, int argc, object *args) /* object self_73161, object r_73128 */
 {
 object r_73128 = args[0];
  
closureN_type c_73337;
object e_73375 [2];
c_73337.hdr.mark = gc_color_red;
 c_73337.hdr.grayed = 0;
c_73337.tag = closureN_tag;
 c_73337.fn = (function_type)__lambda_28;
c_73337.num_args = 1;
c_73337.num_elements = 2;
c_73337.elements = (object *)e_73375;
c_73337.elements[0] = ((closureN)self_73161)->elements[0];
c_73337.elements[1] = ((closureN)self_73161)->elements[1];

return_closcall2(data,  __glo_display_scheme_write,  &c_73337, r_73128);; 
}

static void __lambda_28(void *data, object self_73162, int argc, object *args) /* object self_73162, object r_73119 */
 {

  
closureN_type c_73339;
object e_73353 [1];
c_73339.hdr.mark = gc_color_red;
 c_73339.hdr.grayed = 0;
c_73339.tag = closureN_tag;
 c_73339.fn = (function_type)__lambda_29;
c_73339.num_args = 0;
c_73339.num_elements = 1;
c_73339.elements = (object *)e_73353;
c_73339.elements[0] = ((closureN)self_73162)->elements[1];


closureN_type c_73354;
object e_73374 [2];
c_73354.hdr.mark = gc_color_red;
 c_73354.hdr.grayed = 0;
c_73354.tag = closureN_tag;
 c_73354.fn = (function_type)__lambda_31;
c_73354.num_args = 1;
c_73354.num_elements = 2;
c_73354.elements = (object *)e_73374;
c_73354.elements[0] = ((closureN)self_73162)->elements[0];
c_73354.elements[1] = ((closureN)self_73162)->elements[1];

return_direct_with_clo1(data,(closure)&c_73339,__lambda_29,  &c_73354);; 
}

static void __lambda_31(void *data, object self_73163, int argc, object *args) /* object self_73163, object r_73120 */
 {

  
closureN_type c_73356;
object e_73366 [2];
c_73356.hdr.mark = gc_color_red;
 c_73356.hdr.grayed = 0;
c_73356.tag = closureN_tag;
 c_73356.fn = (function_type)__lambda_32;
c_73356.num_args = 1;
c_73356.num_elements = 2;
c_73356.elements = (object *)e_73366;
c_73356.elements[0] = ((closureN)self_73163)->elements[0];
c_73356.elements[1] = ((closureN)self_73163)->elements[1];


mclosure0(c_73367, (function_type)__lambda_34);c_73367.num_args = 1;
return_direct_with_clo1(data,(closure)&c_73356,__lambda_32,  &c_73367);; 
}

static void __lambda_34(void *data, object self_73164, int argc, object *args) /* object self_73164, object k_73123, object o_7323_7357 */
 {
 object k_73123 = args[0]; object o_7323_7357 = args[1];
  
closureN_type c_73369;
object e_73373 [1];
c_73369.hdr.mark = gc_color_red;
 c_73369.hdr.grayed = 0;
c_73369.tag = closureN_tag;
 c_73369.fn = (function_type)__lambda_35;
c_73369.num_args = 1;
c_73369.num_elements = 1;
c_73369.elements = (object *)e_73373;
c_73369.elements[0] = k_73123;

return_closcall2(data,  __glo_write_scheme_write,  &c_73369, o_7323_7357);; 
}

static void __lambda_35(void *data, object self_73165, int argc, object *args) /* object self_73165, object r_73124 */
 {

  
make_utf8_string_with_len(c_73372, " ", 1, 1);
return_closcall2(data,  __glo_display_scheme_write,  ((closureN)self_73165)->elements[0], &c_73372);; 
}

static void __lambda_32(void *data, object self_73166, int argc, object *args) /* object self_73166, object r_73121 */
 {
 object r_73121 = args[0];
  
closureN_type c_73358;
object e_73362 [2];
c_73358.hdr.mark = gc_color_red;
 c_73358.hdr.grayed = 0;
c_73358.tag = closureN_tag;
 c_73358.fn = (function_type)__lambda_33;
c_73358.num_args = 1;
c_73358.num_elements = 2;
c_73358.elements = (object *)e_73362;
c_73358.elements[0] = ((closureN)self_73166)->elements[0];
c_73358.elements[1] = r_73121;



return_closcall2(data,  __glo_error_91object_91irritants_scheme_base,  &c_73358, car(((closureN)self_73166)->elements[1]));; 
}

static void __lambda_33(void *data, object self_73167, int argc, object *args) /* object self_73167, object r_73122 */
 {
 object r_73122 = args[0];
  return_closcall3(data,  __glo_Cyc_91for_91each_91loop_911_scheme_base,  ((closureN)self_73167)->elements[0], ((closureN)self_73167)->elements[1], r_73122);; 
}

static void __lambda_29(void *data, object self_73168, int argc, object *args) /* object self_73168, object k_73125 */
 {
 object k_73125 = args[0];
  
closureN_type c_73341;
object e_73349 [1];
c_73341.hdr.mark = gc_color_red;
 c_73341.hdr.grayed = 0;
c_73341.tag = closureN_tag;
 c_73341.fn = (function_type)__lambda_30;
c_73341.num_args = 1;
c_73341.num_elements = 1;
c_73341.elements = (object *)e_73349;
c_73341.elements[0] = k_73125;



return_closcall2(data,  __glo_error_91object_91irritants_scheme_base,  &c_73341, car(((closureN)self_73168)->elements[0]));; 
}

static void __lambda_30(void *data, object self_73169, int argc, object *args) /* object self_73169, object r_73127 */
 {
 object r_73127 = args[0];
    
if( (boolean_f != Cyc_is_null(r_73127)) ){ 
  return_closcall1(data,  ((closureN)self_73169)->elements[0],  Cyc_VOID);
} else { 
  
make_utf8_string_with_len(c_73348, ": ", 2, 2);
return_closcall2(data,  __glo_display_scheme_write,  ((closureN)self_73169)->elements[0], &c_73348);}
;; 
}

static void __lambda_8(void *data, object self_73182, int argc, object *args) /* object self_73182, object r_7396 */
 {
 object r_7396 = args[0];
  
closureN_type c_73271;
object e_73275 [2];
c_73271.hdr.mark = gc_color_red;
 c_73271.hdr.grayed = 0;
c_73271.tag = closureN_tag;
 c_73271.fn = (function_type)__lambda_9;
c_73271.num_args = 1;
c_73271.num_elements = 2;
c_73271.elements = (object *)e_73275;
c_73271.elements[0] = ((closureN)self_73182)->elements[0];
c_73271.elements[1] = r_7396;


mclosure0(c_73276, (function_type)__lambda_10);c_73276.num_args = 0;
return_direct_with_clo1(data,(closure)&c_73271,__lambda_9,  &c_73276);; 
}

static void __lambda_10(void *data, object self_73183, int argc, object *args) /* object self_73183, object k_7398 */
 {
 object k_7398 = args[0];
  
closureN_type c_73278;
object e_73321 [1];
c_73278.hdr.mark = gc_color_red;
 c_73278.hdr.grayed = 0;
c_73278.tag = closureN_tag;
 c_73278.fn = (function_type)__lambda_11;
c_73278.num_args = 1;
c_73278.num_elements = 1;
c_73278.elements = (object *)e_73321;
c_73278.elements[0] = k_7398;

return_closcall1(data,  __glo_get_91input,  &c_73278);; 
}

static void __lambda_11(void *data, object self_73184, int argc, object *args) /* object self_73184, object str_7329_7359 */
 {
 object str_7329_7359 = args[0];
  
closureN_type c_73280;
object e_73312 [1];
c_73280.hdr.mark = gc_color_red;
 c_73280.hdr.grayed = 0;
c_73280.tag = closureN_tag;
 c_73280.fn = (function_type)__lambda_12;
c_73280.num_args = 0;
c_73280.num_elements = 1;
c_73280.elements = (object *)e_73312;
c_73280.elements[0] = str_7329_7359;


closureN_type c_73313;
object e_73320 [1];
c_73313.hdr.mark = gc_color_red;
 c_73313.hdr.grayed = 0;
c_73313.tag = closureN_tag;
 c_73313.fn = (function_type)__lambda_20;
c_73313.num_args = 1;
c_73313.num_elements = 1;
c_73313.elements = (object *)e_73320;
c_73313.elements[0] = ((closureN)self_73184)->elements[0];

return_direct_with_clo1(data,(closure)&c_73280,__lambda_12,  &c_73313);; 
}

static void __lambda_20(void *data, object self_73185, int argc, object *args) /* object self_73185, object r_7399 */
 {

  
closureN_type c_73315;
object e_73318 [1];
c_73315.hdr.mark = gc_color_red;
 c_73315.hdr.grayed = 0;
c_73315.tag = closureN_tag;
 c_73315.fn = (function_type)__lambda_21;
c_73315.num_args = 1;
c_73315.num_elements = 1;
c_73315.elements = (object *)e_73318;
c_73315.elements[0] = ((closureN)self_73185)->elements[0];


make_double(c_73319, 0.1);
return_closcall2(data,  __glo_thread_91sleep_67_srfi_18,  &c_73315, &c_73319);; 
}

static void __lambda_21(void *data, object self_73186, int argc, object *args) /* object self_73186, object r_73100 */
 {

  return_closcall1(data,  __glo_loop,  ((closureN)self_73186)->elements[0]);; 
}

static void __lambda_12(void *data, object self_73187, int argc, object *args) /* object self_73187, object k_73102 */
 {
 object k_73102 = args[0];
  if( (boolean_f != ((closureN)self_73187)->elements[0]) ){ 
  
closureN_type c_73283;
object e_73309 [1];
c_73283.hdr.mark = gc_color_red;
 c_73283.hdr.grayed = 0;
c_73283.tag = closureN_tag;
 c_73283.fn = (function_type)__lambda_13;
c_73283.num_args = 1;
c_73283.num_elements = 1;
c_73283.elements = (object *)e_73309;
c_73283.elements[0] = k_73102;

return_closcall2(data,  __glo_open_91input_91string_scheme_base,  &c_73283, ((closureN)self_73187)->elements[0]);
} else { 
  return_closcall1(data,  k_73102,  Cyc_VOID);}
;; 
}

static void __lambda_13(void *data, object self_73188, int argc, object *args) /* object self_73188, object fp_7332_7360 */
 {
 object fp_7332_7360 = args[0];
  
closureN_type c_73285;
object e_73308 [2];
c_73285.hdr.mark = gc_color_red;
 c_73285.hdr.grayed = 0;
c_73285.tag = closureN_tag;
 c_73285.fn = (function_type)__lambda_14;
c_73285.num_args = 1;
c_73285.num_elements = 2;
c_73285.elements = (object *)e_73308;
c_73285.elements[0] = fp_7332_7360;
c_73285.elements[1] = ((closureN)self_73188)->elements[0];

return_closcall2(data,  __glo_read_91all_scheme_read,  &c_73285, fp_7332_7360);; 
}

static void __lambda_14(void *data, object self_73189, int argc, object *args) /* object self_73189, object sexp_91lis_7335_7361 */
 {
 object sexp_91lis_7335_7361 = args[0];
  
closureN_type c_73287;
object e_73298 [3];
c_73287.hdr.mark = gc_color_red;
 c_73287.hdr.grayed = 0;
c_73287.tag = closureN_tag;
 c_73287.fn = (function_type)__lambda_15;
c_73287.num_args = 1;
c_73287.num_elements = 3;
c_73287.elements = (object *)e_73298;
c_73287.elements[0] = ((closureN)self_73189)->elements[0];
c_73287.elements[1] = ((closureN)self_73189)->elements[1];
c_73287.elements[2] = sexp_91lis_7335_7361;


mclosure0(c_73299, (function_type)__lambda_17);c_73299.num_args = 1;
return_direct_with_clo1(data,(closure)&c_73287,__lambda_15,  &c_73299);; 
}

static void __lambda_17(void *data, object self_73190, int argc, object *args) /* object self_73190, object k_73108, object sexp_7337_7362 */
 {
 object k_73108 = args[0]; object sexp_7337_7362 = args[1];
  
closureN_type c_73301;
object e_73307 [1];
c_73301.hdr.mark = gc_color_red;
 c_73301.hdr.grayed = 0;
c_73301.tag = closureN_tag;
 c_73301.fn = (function_type)__lambda_18;
c_73301.num_args = 1;
c_73301.num_elements = 1;
c_73301.elements = (object *)e_73307;
c_73301.elements[0] = k_73108;

return_closcall2(data,  __glo_eval_scheme_eval,  &c_73301, sexp_7337_7362);; 
}

static void __lambda_18(void *data, object self_73191, int argc, object *args) /* object self_73191, object obj_7338_7363 */
 {
 object obj_7338_7363 = args[0];
  
closureN_type c_73303;
object e_73306 [1];
c_73303.hdr.mark = gc_color_red;
 c_73303.hdr.grayed = 0;
c_73303.tag = closureN_tag;
 c_73303.fn = (function_type)__lambda_19;
c_73303.num_args = 1;
c_73303.num_elements = 1;
c_73303.elements = (object *)e_73306;
c_73303.elements[0] = ((closureN)self_73191)->elements[0];

return_closcall2(data,  __glo_write_scheme_write,  &c_73303, obj_7338_7363);; 
}

static void __lambda_19(void *data, object self_73192, int argc, object *args) /* object self_73192, object r_73110 */
 {

  return_closcall1(data,  __glo_newline_scheme_base,  ((closureN)self_73192)->elements[0]);; 
}

static void __lambda_15(void *data, object self_73193, int argc, object *args) /* object self_73193, object r_73107 */
 {
 object r_73107 = args[0];
  
closureN_type c_73289;
object e_73296 [2];
c_73289.hdr.mark = gc_color_red;
 c_73289.hdr.grayed = 0;
c_73289.tag = closureN_tag;
 c_73289.fn = (function_type)__lambda_16;
c_73289.num_args = 1;
c_73289.num_elements = 2;
c_73289.elements = (object *)e_73296;
c_73289.elements[0] = ((closureN)self_73193)->elements[0];
c_73289.elements[1] = ((closureN)self_73193)->elements[1];

return_closcall3(data,  __glo_Cyc_91for_91each_91loop_911_scheme_base,  &c_73289, r_73107, ((closureN)self_73193)->elements[2]);; 
}

static void __lambda_16(void *data, object self_73194, int argc, object *args) /* object self_73194, object r_73106 */
 {

  
  Cyc_io_close_port(data, ((closureN)self_73194)->elements[0]);return_closcall1(data,  __glo_ready_91for_91more_91input,  ((closureN)self_73194)->elements[1]);;; 
}

static void __lambda_9(void *data, object self_73195, int argc, object *args) /* object self_73195, object r_7397 */
 {
 object r_7397 = args[0];
  return_closcall3(data,  __glo_with_91exception_91handler_scheme_base,  ((closureN)self_73195)->elements[0], ((closureN)self_73195)->elements[1], r_7397);; 
}

static void __lambda_6(void *data, object self_73196, int argc, object *args) /* object self_73196, object r_7394 */
 {
 object r_7394 = args[0];
  return_closcall2(data,  __glo_call_95cc_scheme_base,  ((closureN)self_73196)->elements[0], r_7394);; 
}

static void __lambda_58(void *data, object _, int argc, object *args) { object k = args[0]; 
    object cmd = args[1];
    MAIN_THREAD_ASYNC_EM_ASM({
      helpLink(UTF8ToString($0));
    }, symbol_desc(cmd));
    return_closcall1(data, k, boolean_f);
   }
static void __lambda_57(void *data, object _, int argc, object *args) { object k = args[0]; 
    MAIN_THREAD_ASYNC_EM_ASM(
      readyForNextCommand();
    );
    return_closcall1(data, k, boolean_f);
   }
static void __lambda_56(void *data, object _, int argc, object *args) { object k = args[0]; 
    /* TODO: use mutex to lock glo_sexp */
    char *s = glo_sexp;
    glo_sexp = NULL;
    /* TODO: unlock */
  
    if (s != NULL) {
      make_utf8_string(data, str, s);
      free(s);
      return_closcall1(data, k, &str); 
    } else {
      return_closcall1(data, k, boolean_f);
    }  }
static void __lambda_2(void *data, object _, int argc, object *args) /* closure _,object k_7383, object opts_7311_7353_raw, ... */
 {
object k_7383 = args[0];
load_varargs(opts_7311_7353, args, 1, argc - 1);
  object r_7384;
  Cyc_st_add(data, "src/terminal.scm:%help");
  
if( (boolean_f != Cyc_is_pair(opts_7311_7353)) ){ 
  
  
  r_7384 = Cyc_is_symbol(Cyc_car(data, opts_7311_7353));
} else { 
  r_7384 = boolean_f;}
;if( (boolean_f != r_7384) ){ 
  
closureN_type c_73236;
object e_73242 [1];
c_73236.hdr.mark = gc_color_red;
 c_73236.hdr.grayed = 0;
c_73236.tag = closureN_tag;
 c_73236.fn = (function_type)__lambda_3;
c_73236.num_args = 1;
c_73236.num_elements = 1;
c_73236.elements = (object *)e_73242;
c_73236.elements[0] = k_7383;



return_closcall2(data,  __glo_display_91help_91for_91cmd,  &c_73236, Cyc_car(data, opts_7311_7353));
} else { 
  
closureN_type c_73246;
object e_73249 [1];
c_73246.hdr.mark = gc_color_red;
 c_73246.hdr.grayed = 0;
c_73246.tag = closureN_tag;
 c_73246.fn = (function_type)__lambda_4;
c_73246.num_args = 1;
c_73246.num_elements = 1;
c_73246.elements = (object *)e_73249;
c_73246.elements[0] = k_7383;


make_utf8_string_with_len(c_73253, "\nType (help) to see this menu.\nType (help object) to find API documentation for object\n\nCyclone\nWebsite: ", 105, 105);

make_utf8_string_with_len(c_73254, "\nUser Manual: ", 14, 14);

make_utf8_string_with_len(c_73255, "/docs/User-Manual\nAPI Documentation: ", 37, 37);

make_utf8_string_with_len(c_73256, "/docs/API\nForum: https://github.com/justinethier/cyclone/discussions\nReport a Bug: https://github.com/justinethier/cyclone/issues\n\nOther Resources\nR7RS Scheme Language Specification: ", 183, 183);

make_utf8_string_with_len(c_73257, "/docs/r7rs.pdf\n\n", 16, 16);

object c_73252 = Cyc_string_append(data,(closure)&c_73246,9,&c_73253, __glo__85site_91url_85, &c_73254, __glo__85site_91url_85, &c_73255, __glo__85site_91url_85, &c_73256, __glo__85site_91url_85, &c_73257);
return_closcall1(data,(closure)&c_73246,  c_73252);}
;; 
}

static void __lambda_4(void *data, object self_73149, int argc, object *args) /* object self_73149, object r_7387 */
 {
 object r_7387 = args[0];
  return_closcall2(data,  __glo_display_scheme_write,  ((closureN)self_73149)->elements[0], r_7387);; 
}

static void __lambda_3(void *data, object self_73148, int argc, object *args) /* object self_73148, object r_7385 */
 {

  
complex_num_type local_73241; 
return_closcall1(data,  ((closureN)self_73148)->elements[0],  ((inline_function_type)
                   ((closure)__glo_void_191_191inline_191_191_scheme_base)->fn)(data,&local_73241));; 
}

static void __lambda_1(void *data, object _, int argc, object *args) /* closure _,object k_7368, object expr_731_7349, object rename_732_7350, object compare_733_7351 */
 {
object k_7368 = args[0]; object expr_731_7349 = args[1];
  Cyc_st_add(data, "src/terminal.scm:help");
  
  
if( (boolean_f != Cyc_num_fast_eq_op(data, Cyc_length(data, expr_731_7349), obj_int2obj(1))) ){ 
  
pair_type local_73209; 
return_closcall1(data,  k_7368,  set_pair_as_expr(&local_73209, quote__75help, NULL));
} else { 
  
pair_type local_73213; 

pair_type local_73216; 

pair_type local_73219; 

pair_type local_73222; 


return_closcall1(data,  k_7368,  set_pair_as_expr(&local_73213, quote__75help, set_pair_as_expr(&local_73216, set_pair_as_expr(&local_73219, quote_quote, set_pair_as_expr(&local_73222, Cyc_cadr(data, expr_731_7349), NULL)), NULL)));}
;; 
}

static void c_entry_pt_first_lambda(void *data, object clo, int argc, object *args);
extern void c_schemecyclonecommon_entry_pt(void *data, object clo, int argc, object* args);
extern void c_schemebase_entry_pt(void *data, object clo, int argc, object* args);
extern void c_srfi18_entry_pt(void *data, object clo, int argc, object* args);
extern void c_schemefile_entry_pt(void *data, object clo, int argc, object* args);
extern void c_scheme_char_entry_pt(void *data, object clo, int argc, object* args);
extern void c_srfi69_entry_pt(void *data, object clo, int argc, object* args);
extern void c_schemewrite_entry_pt(void *data, object clo, int argc, object* args);
extern void c_schemecyclonehashset_entry_pt(void *data, object clo, int argc, object* args);
extern void c_schemecycloneprimitives_entry_pt(void *data, object clo, int argc, object* args);
extern void c_schemeprocess_91context_entry_pt(void *data, object clo, int argc, object* args);
extern void c_schemeread_entry_pt(void *data, object clo, int argc, object* args);
extern void c_schemecycloneutil_entry_pt(void *data, object clo, int argc, object* args);
extern void c_schemecyclonelibraries_entry_pt(void *data, object clo, int argc, object* args);
extern void c_schemeeval_entry_pt(void *data, object clo, int argc, object* args);
static void c_entry_pt(void *data, object clo, int argc, object *args) { 
Cyc_set_globals_changed((gc_thread_data *)data);
  quote_quote = find_or_add_symbol("quote");
  quote__75help = find_or_add_symbol("%help");

  add_global("__glo_loop", (object *) &__glo_loop);
  add_global("__glo_display_91help_91for_91cmd", (object *) &__glo_display_91help_91for_91cmd);
  add_global("__glo_ready_91for_91more_91input", (object *) &__glo_ready_91for_91more_91input);
  add_global("__glo_get_91input", (object *) &__glo_get_91input);
  add_global("__glo__75help", (object *) &__glo__75help);
  add_global("__glo_help", (object *) &__glo_help);
  add_global("__glo__85site_91url_85", (object *) &__glo__85site_91url_85);
  mclosure0(c_73261, (function_type)__lambda_5);c_73261.num_args = 0; 
  __glo_loop = &c_73261; 
  mclosure0(c_73260, (function_type)__lambda_58);c_73260.num_args = 0; 
  __glo_display_91help_91for_91cmd = &c_73260; 
  mclosure0(c_73259, (function_type)__lambda_57);c_73259.num_args = 0; 
  __glo_ready_91for_91more_91input = &c_73259; 
  mclosure0(c_73258, (function_type)__lambda_56);c_73258.num_args = 0; 
  __glo_get_91input = &c_73258; 
  mclosure0(c_73225, (function_type)__lambda_2);c_73225.num_args = 0; 
  __glo__75help = &c_73225; 
  mmacro(c_73201, (function_type)__lambda_1);c_73201.num_args = 3; 
  __glo_help = &c_73201; 
  make_utf8_string_with_len(c_73200, "http://justinethier.github.io/cyclone", 37, 37); 
  __glo__85site_91url_85 = &c_73200; 

  make_cvar(cvar_73501, (object *)&__glo_loop);make_pair(pair_73502, find_or_add_symbol("loop"), &cvar_73501);
  make_cvar(cvar_73503, (object *)&__glo_display_91help_91for_91cmd);make_pair(pair_73504, find_or_add_symbol("display-help-for-cmd"), &cvar_73503);
  make_cvar(cvar_73505, (object *)&__glo_ready_91for_91more_91input);make_pair(pair_73506, find_or_add_symbol("ready-for-more-input"), &cvar_73505);
  make_cvar(cvar_73507, (object *)&__glo_get_91input);make_pair(pair_73508, find_or_add_symbol("get-input"), &cvar_73507);
  make_cvar(cvar_73509, (object *)&__glo__75help);make_pair(pair_73510, find_or_add_symbol("%help"), &cvar_73509);
  make_cvar(cvar_73511, (object *)&__glo_help);make_pair(pair_73512, find_or_add_symbol("help"), &cvar_73511);
  make_cvar(cvar_73513, (object *)&__glo__85site_91url_85);make_pair(pair_73514, find_or_add_symbol("*site-url*"), &cvar_73513);
make_pair(c_73521, &pair_73502,Cyc_global_variables);
make_pair(c_73520, &pair_73504, &c_73521);
make_pair(c_73519, &pair_73506, &c_73520);
make_pair(c_73518, &pair_73508, &c_73519);
make_pair(c_73517, &pair_73510, &c_73518);
make_pair(c_73516, &pair_73512, &c_73517);
make_pair(c_73515, &pair_73514, &c_73516);
Cyc_global_variables = &c_73515;
mclosure1(c_done, c_entry_pt_first_lambda, &c_done);
mclosure1(c_73522, c_schemeeval_entry_pt, &c_done);
mclosure1(c_73523, c_schemecyclonelibraries_entry_pt, &c_73522);
mclosure1(c_73524, c_schemecycloneutil_entry_pt, &c_73523);
mclosure1(c_73525, c_schemeread_entry_pt, &c_73524);
mclosure1(c_73526, c_schemeprocess_91context_entry_pt, &c_73525);
mclosure1(c_73527, c_schemecycloneprimitives_entry_pt, &c_73526);
mclosure1(c_73528, c_schemecyclonehashset_entry_pt, &c_73527);
mclosure1(c_73529, c_schemewrite_entry_pt, &c_73528);
mclosure1(c_73530, c_srfi69_entry_pt, &c_73529);
mclosure1(c_73531, c_scheme_char_entry_pt, &c_73530);
mclosure1(c_73532, c_schemefile_entry_pt, &c_73531);
mclosure1(c_73533, c_srfi18_entry_pt, &c_73532);
mclosure1(c_73534, c_schemebase_entry_pt, &c_73533);
mclosure1(c_73535, c_schemecyclonecommon_entry_pt, &c_73534);
 object buf[1]; buf[0] = &c_73535; (c_73535.fn)(data, &c_73535, 1, buf);
}
static void c_entry_pt_first_lambda(void *data, object clo, int argc, object *args) {
  
    
    
    
    
    
    
    
mclosure0(c_73492, (function_type)__lambda_52);c_73492.num_args = 1;
return_closcall1(data,  __glo__75help,  &c_73492);
;
}
int main(int argc, char **argv, char **envp)
{gc_thread_data *thd;
 long stack_size = global_stack_size = STACK_SIZE;
 long heap_size = global_heap_size = HEAP_SIZE;
 init_polyfills();
 mclosure0(clos_halt,&Cyc_halt);  // Halt if final closure is reached
 mclosure0(entry_pt,&c_entry_pt); // First function to execute
 _cyc_argc = argc;
 _cyc_argv = argv;
 set_env_variables(envp);
 gc_initialize();
 thd = malloc(sizeof(gc_thread_data));
 gc_thread_data_init(thd, 0, (char *) &stack_size, stack_size);
 thd->gc_cont = &entry_pt;
 thd->gc_args[0] = &clos_halt;
 thd->gc_num_args = 1;
 thd->thread_id = pthread_self();
 gc_add_mutator(thd);
 Cyc_heap_init(heap_size);
 thd->thread_state = CYC_THREAD_STATE_RUNNABLE;
 Cyc_start_trampoline(thd);
 return 0;}
